<?php



/**
 * This class defines the structure of the 'orden_ubicacion' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/30/25 22:58:34
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class OrdenUbicacionTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.OrdenUbicacionTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('orden_ubicacion');
        $this->setPhpName('OrdenUbicacion');
        $this->setClassname('OrdenUbicacion');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('TIENDA_ID', 'TiendaId', 'INTEGER', 'tienda', 'ID', false, null, null);
        $this->addForeignKey('PRODUCTO_ID', 'ProductoId', 'INTEGER', 'producto', 'ID', false, null, null);
        $this->addColumn('UBICACION_ID', 'UbicacionId', 'VARCHAR', false, 50, null);
        $this->addForeignKey('ORDEN_COTIZACION_ID', 'OrdenCotizacionId', 'INTEGER', 'orden_cotizacion', 'ID', false, null, null);
        $this->addColumn('PROCESADO', 'Procesado', 'BOOLEAN', false, 1, false);
        $this->addColumn('CANTIDAD', 'Cantidad', 'INTEGER', false, null, null);
        $this->addColumn('TIENDA_UBICA', 'TiendaUbica', 'INTEGER', false, null, null);
        $this->addForeignKey('VENDEDOR_PRODUCTO_ID', 'VendedorProductoId', 'INTEGER', 'vendedor_producto', 'ID', false, null, null);
        $this->addForeignKey('ORDEN_VENDEDOR_ID', 'OrdenVendedorId', 'INTEGER', 'orden_vendedor', 'ID', false, null, null);
        $this->addForeignKey('SALIDA_PRODUCTO_ID', 'SalidaProductoId', 'INTEGER', 'salida_producto', 'ID', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Tienda', 'Tienda', RelationMap::MANY_TO_ONE, array('tienda_id' => 'id', ), null, null);
        $this->addRelation('Producto', 'Producto', RelationMap::MANY_TO_ONE, array('producto_id' => 'id', ), null, null);
        $this->addRelation('OrdenCotizacion', 'OrdenCotizacion', RelationMap::MANY_TO_ONE, array('orden_cotizacion_id' => 'id', ), null, null);
        $this->addRelation('VendedorProducto', 'VendedorProducto', RelationMap::MANY_TO_ONE, array('vendedor_producto_id' => 'id', ), null, null);
        $this->addRelation('OrdenVendedor', 'OrdenVendedor', RelationMap::MANY_TO_ONE, array('orden_vendedor_id' => 'id', ), null, null);
        $this->addRelation('SalidaProducto', 'SalidaProducto', RelationMap::MANY_TO_ONE, array('salida_producto_id' => 'id', ), null, null);
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // OrdenUbicacionTableMap
