<?php



/**
 * This class defines the structure of the 'usuario_report' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/26/25 01:36:36
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class UsuarioReportTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.UsuarioReportTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('usuario_report');
        $this->setPhpName('UsuarioReport');
        $this->setClassname('UsuarioReport');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('EMPRESA_ID', 'EmpresaId', 'INTEGER', 'empresa', 'ID', false, null, null);
        $this->addColumn('TIPO_LETRA', 'TipoLetra', 'VARCHAR', false, 50, null);
        $this->addColumn('PAPEL', 'Papel', 'VARCHAR', false, 50, null);
        $this->addColumn('ORIENTACION', 'Orientacion', 'VARCHAR', false, 50, null);
        $this->addColumn('LOGO_TAMANIO', 'LogoTamanio', 'VARCHAR', false, 50, null);
        $this->addColumn('LOGO_POSICION', 'LogoPosicion', 'VARCHAR', false, 90, null);
        $this->addColumn('LETRA_TITULO_NO', 'LetraTituloNo', 'INTEGER', false, null, null);
        $this->addColumn('LETRA_DETALLE_NO', 'LetraDetalleNo', 'INTEGER', false, null, null);
        $this->addColumn('LETRA_TITULO_BOLD', 'LetraTituloBold', 'BOOLEAN', false, 1, true);
        $this->addColumn('LETRA_DETALLE_BOLD', 'LetraDetalleBold', 'BOOLEAN', false, 1, true);
        $this->addColumn('LETRA_TITULO_COLOR', 'LetraTituloColor', 'VARCHAR', false, 10, null);
        $this->addColumn('LETRA_DETALLE_COLOR', 'LetraDetalleColor', 'VARCHAR', false, 10, null);
        $this->addColumn('UNA_LINEA', 'UnaLinea', 'BOOLEAN', false, 1, false);
        $this->addColumn('TIPO_TABLA', 'TipoTabla', 'VARCHAR', false, 50, null);
        $this->addColumn('BORDER_COLOR', 'BorderColor', 'VARCHAR', false, 50, null);
        $this->addColumn('FONDO_COLOR_ENCABEZADO', 'FondoColorEncabezado', 'VARCHAR', false, 50, null);
        $this->addColumn('FONDO_COLOR_DETALLE', 'FondoColorDetalle', 'VARCHAR', false, 50, null);
        $this->addColumn('MARCA_AGUA', 'MarcaAgua', 'INTEGER', false, null, 0);
        $this->addColumn('FONDO', 'Fondo', 'VARCHAR', false, 150, null);
        $this->addColumn('LOGO', 'Logo', 'VARCHAR', false, 150, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Empresa', 'Empresa', RelationMap::MANY_TO_ONE, array('empresa_id' => 'id', ), null, null);
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // UsuarioReportTableMap
