<?php


/**
 * Base class that represents a query for the 'tienda_comision' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/30/25 22:58:34
 *
 * @method TiendaComisionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method TiendaComisionQuery orderByNombreTienda($order = Criteria::ASC) Order by the nombre_tienda column
 * @method TiendaComisionQuery orderByMinimo($order = Criteria::ASC) Order by the minimo column
 * @method TiendaComisionQuery orderByMaximo($order = Criteria::ASC) Order by the maximo column
 * @method TiendaComisionQuery orderByTipo($order = Criteria::ASC) Order by the tipo column
 * @method TiendaComisionQuery orderByValor($order = Criteria::ASC) Order by the valor column
 *
 * @method TiendaComisionQuery groupById() Group by the id column
 * @method TiendaComisionQuery groupByNombreTienda() Group by the nombre_tienda column
 * @method TiendaComisionQuery groupByMinimo() Group by the minimo column
 * @method TiendaComisionQuery groupByMaximo() Group by the maximo column
 * @method TiendaComisionQuery groupByTipo() Group by the tipo column
 * @method TiendaComisionQuery groupByValor() Group by the valor column
 *
 * @method TiendaComisionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method TiendaComisionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method TiendaComisionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method TiendaComision findOne(PropelPDO $con = null) Return the first TiendaComision matching the query
 * @method TiendaComision findOneOrCreate(PropelPDO $con = null) Return the first TiendaComision matching the query, or a new TiendaComision object populated from the query conditions when no match is found
 *
 * @method TiendaComision findOneById(int $id) Return the first TiendaComision filtered by the id column
 * @method TiendaComision findOneByNombreTienda(string $nombre_tienda) Return the first TiendaComision filtered by the nombre_tienda column
 * @method TiendaComision findOneByMinimo(double $minimo) Return the first TiendaComision filtered by the minimo column
 * @method TiendaComision findOneByMaximo(double $maximo) Return the first TiendaComision filtered by the maximo column
 * @method TiendaComision findOneByTipo(string $tipo) Return the first TiendaComision filtered by the tipo column
 * @method TiendaComision findOneByValor(string $valor) Return the first TiendaComision filtered by the valor column
 *
 * @method array findById(int $id) Return TiendaComision objects filtered by the id column
 * @method array findByNombreTienda(string $nombre_tienda) Return TiendaComision objects filtered by the nombre_tienda column
 * @method array findByMinimo(double $minimo) Return TiendaComision objects filtered by the minimo column
 * @method array findByMaximo(double $maximo) Return TiendaComision objects filtered by the maximo column
 * @method array findByTipo(string $tipo) Return TiendaComision objects filtered by the tipo column
 * @method array findByValor(string $valor) Return TiendaComision objects filtered by the valor column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseTiendaComisionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseTiendaComisionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'TiendaComision', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TiendaComisionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     TiendaComisionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TiendaComisionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TiendaComisionQuery) {
            return $criteria;
        }
        $query = new TiendaComisionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   TiendaComision|TiendaComision[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TiendaComisionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TiendaComisionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   TiendaComision A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `NOMBRE_TIENDA`, `MINIMO`, `MAXIMO`, `TIPO`, `VALOR` FROM `tienda_comision` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new TiendaComision();
            $obj->hydrate($row);
            TiendaComisionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return TiendaComision|TiendaComision[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|TiendaComision[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TiendaComisionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TiendaComisionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(TiendaComisionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the nombre_tienda column
     *
     * Example usage:
     * <code>
     * $query->filterByNombreTienda('fooValue');   // WHERE nombre_tienda = 'fooValue'
     * $query->filterByNombreTienda('%fooValue%'); // WHERE nombre_tienda LIKE '%fooValue%'
     * </code>
     *
     * @param     string $nombreTienda The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterByNombreTienda($nombreTienda = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($nombreTienda)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $nombreTienda)) {
                $nombreTienda = str_replace('*', '%', $nombreTienda);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TiendaComisionPeer::NOMBRE_TIENDA, $nombreTienda, $comparison);
    }

    /**
     * Filter the query on the minimo column
     *
     * Example usage:
     * <code>
     * $query->filterByMinimo(1234); // WHERE minimo = 1234
     * $query->filterByMinimo(array(12, 34)); // WHERE minimo IN (12, 34)
     * $query->filterByMinimo(array('min' => 12)); // WHERE minimo > 12
     * </code>
     *
     * @param     mixed $minimo The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterByMinimo($minimo = null, $comparison = null)
    {
        if (is_array($minimo)) {
            $useMinMax = false;
            if (isset($minimo['min'])) {
                $this->addUsingAlias(TiendaComisionPeer::MINIMO, $minimo['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($minimo['max'])) {
                $this->addUsingAlias(TiendaComisionPeer::MINIMO, $minimo['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TiendaComisionPeer::MINIMO, $minimo, $comparison);
    }

    /**
     * Filter the query on the maximo column
     *
     * Example usage:
     * <code>
     * $query->filterByMaximo(1234); // WHERE maximo = 1234
     * $query->filterByMaximo(array(12, 34)); // WHERE maximo IN (12, 34)
     * $query->filterByMaximo(array('min' => 12)); // WHERE maximo > 12
     * </code>
     *
     * @param     mixed $maximo The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterByMaximo($maximo = null, $comparison = null)
    {
        if (is_array($maximo)) {
            $useMinMax = false;
            if (isset($maximo['min'])) {
                $this->addUsingAlias(TiendaComisionPeer::MAXIMO, $maximo['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($maximo['max'])) {
                $this->addUsingAlias(TiendaComisionPeer::MAXIMO, $maximo['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TiendaComisionPeer::MAXIMO, $maximo, $comparison);
    }

    /**
     * Filter the query on the tipo column
     *
     * Example usage:
     * <code>
     * $query->filterByTipo('fooValue');   // WHERE tipo = 'fooValue'
     * $query->filterByTipo('%fooValue%'); // WHERE tipo LIKE '%fooValue%'
     * </code>
     *
     * @param     string $tipo The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterByTipo($tipo = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($tipo)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $tipo)) {
                $tipo = str_replace('*', '%', $tipo);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TiendaComisionPeer::TIPO, $tipo, $comparison);
    }

    /**
     * Filter the query on the valor column
     *
     * Example usage:
     * <code>
     * $query->filterByValor('fooValue');   // WHERE valor = 'fooValue'
     * $query->filterByValor('%fooValue%'); // WHERE valor LIKE '%fooValue%'
     * </code>
     *
     * @param     string $valor The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function filterByValor($valor = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($valor)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $valor)) {
                $valor = str_replace('*', '%', $valor);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TiendaComisionPeer::VALOR, $valor, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   TiendaComision $tiendaComision Object to remove from the list of results
     *
     * @return TiendaComisionQuery The current query, for fluid interface
     */
    public function prune($tiendaComision = null)
    {
        if ($tiendaComision) {
            $this->addUsingAlias(TiendaComisionPeer::ID, $tiendaComision->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
