<?php


/**
 * Base class that represents a query for the 'producto_ubicacion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/28/25 02:48:07
 *
 * @method ProductoUbicacionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method ProductoUbicacionQuery orderByEmpresaId($order = Criteria::ASC) Order by the empresa_id column
 * @method ProductoUbicacionQuery orderByProductoId($order = Criteria::ASC) Order by the producto_id column
 * @method ProductoUbicacionQuery orderByCantidad($order = Criteria::ASC) Order by the cantidad column
 * @method ProductoUbicacionQuery orderByTiendaId($order = Criteria::ASC) Order by the tienda_id column
 * @method ProductoUbicacionQuery orderByUbicacion($order = Criteria::ASC) Order by the ubicacion column
 * @method ProductoUbicacionQuery orderByTransito($order = Criteria::ASC) Order by the transito column
 *
 * @method ProductoUbicacionQuery groupById() Group by the id column
 * @method ProductoUbicacionQuery groupByEmpresaId() Group by the empresa_id column
 * @method ProductoUbicacionQuery groupByProductoId() Group by the producto_id column
 * @method ProductoUbicacionQuery groupByCantidad() Group by the cantidad column
 * @method ProductoUbicacionQuery groupByTiendaId() Group by the tienda_id column
 * @method ProductoUbicacionQuery groupByUbicacion() Group by the ubicacion column
 * @method ProductoUbicacionQuery groupByTransito() Group by the transito column
 *
 * @method ProductoUbicacionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method ProductoUbicacionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method ProductoUbicacionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method ProductoUbicacionQuery leftJoinEmpresa($relationAlias = null) Adds a LEFT JOIN clause to the query using the Empresa relation
 * @method ProductoUbicacionQuery rightJoinEmpresa($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Empresa relation
 * @method ProductoUbicacionQuery innerJoinEmpresa($relationAlias = null) Adds a INNER JOIN clause to the query using the Empresa relation
 *
 * @method ProductoUbicacionQuery leftJoinProducto($relationAlias = null) Adds a LEFT JOIN clause to the query using the Producto relation
 * @method ProductoUbicacionQuery rightJoinProducto($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Producto relation
 * @method ProductoUbicacionQuery innerJoinProducto($relationAlias = null) Adds a INNER JOIN clause to the query using the Producto relation
 *
 * @method ProductoUbicacionQuery leftJoinTienda($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tienda relation
 * @method ProductoUbicacionQuery rightJoinTienda($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tienda relation
 * @method ProductoUbicacionQuery innerJoinTienda($relationAlias = null) Adds a INNER JOIN clause to the query using the Tienda relation
 *
 * @method ProductoUbicacion findOne(PropelPDO $con = null) Return the first ProductoUbicacion matching the query
 * @method ProductoUbicacion findOneOrCreate(PropelPDO $con = null) Return the first ProductoUbicacion matching the query, or a new ProductoUbicacion object populated from the query conditions when no match is found
 *
 * @method ProductoUbicacion findOneById(int $id) Return the first ProductoUbicacion filtered by the id column
 * @method ProductoUbicacion findOneByEmpresaId(int $empresa_id) Return the first ProductoUbicacion filtered by the empresa_id column
 * @method ProductoUbicacion findOneByProductoId(int $producto_id) Return the first ProductoUbicacion filtered by the producto_id column
 * @method ProductoUbicacion findOneByCantidad(int $cantidad) Return the first ProductoUbicacion filtered by the cantidad column
 * @method ProductoUbicacion findOneByTiendaId(int $tienda_id) Return the first ProductoUbicacion filtered by the tienda_id column
 * @method ProductoUbicacion findOneByUbicacion(string $ubicacion) Return the first ProductoUbicacion filtered by the ubicacion column
 * @method ProductoUbicacion findOneByTransito(int $transito) Return the first ProductoUbicacion filtered by the transito column
 *
 * @method array findById(int $id) Return ProductoUbicacion objects filtered by the id column
 * @method array findByEmpresaId(int $empresa_id) Return ProductoUbicacion objects filtered by the empresa_id column
 * @method array findByProductoId(int $producto_id) Return ProductoUbicacion objects filtered by the producto_id column
 * @method array findByCantidad(int $cantidad) Return ProductoUbicacion objects filtered by the cantidad column
 * @method array findByTiendaId(int $tienda_id) Return ProductoUbicacion objects filtered by the tienda_id column
 * @method array findByUbicacion(string $ubicacion) Return ProductoUbicacion objects filtered by the ubicacion column
 * @method array findByTransito(int $transito) Return ProductoUbicacion objects filtered by the transito column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseProductoUbicacionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseProductoUbicacionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'ProductoUbicacion', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new ProductoUbicacionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     ProductoUbicacionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return ProductoUbicacionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof ProductoUbicacionQuery) {
            return $criteria;
        }
        $query = new ProductoUbicacionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   ProductoUbicacion|ProductoUbicacion[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = ProductoUbicacionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(ProductoUbicacionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   ProductoUbicacion A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `EMPRESA_ID`, `PRODUCTO_ID`, `CANTIDAD`, `TIENDA_ID`, `UBICACION`, `TRANSITO` FROM `producto_ubicacion` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new ProductoUbicacion();
            $obj->hydrate($row);
            ProductoUbicacionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return ProductoUbicacion|ProductoUbicacion[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|ProductoUbicacion[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(ProductoUbicacionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(ProductoUbicacionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(ProductoUbicacionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the empresa_id column
     *
     * Example usage:
     * <code>
     * $query->filterByEmpresaId(1234); // WHERE empresa_id = 1234
     * $query->filterByEmpresaId(array(12, 34)); // WHERE empresa_id IN (12, 34)
     * $query->filterByEmpresaId(array('min' => 12)); // WHERE empresa_id > 12
     * </code>
     *
     * @see       filterByEmpresa()
     *
     * @param     mixed $empresaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByEmpresaId($empresaId = null, $comparison = null)
    {
        if (is_array($empresaId)) {
            $useMinMax = false;
            if (isset($empresaId['min'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::EMPRESA_ID, $empresaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($empresaId['max'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::EMPRESA_ID, $empresaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ProductoUbicacionPeer::EMPRESA_ID, $empresaId, $comparison);
    }

    /**
     * Filter the query on the producto_id column
     *
     * Example usage:
     * <code>
     * $query->filterByProductoId(1234); // WHERE producto_id = 1234
     * $query->filterByProductoId(array(12, 34)); // WHERE producto_id IN (12, 34)
     * $query->filterByProductoId(array('min' => 12)); // WHERE producto_id > 12
     * </code>
     *
     * @see       filterByProducto()
     *
     * @param     mixed $productoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByProductoId($productoId = null, $comparison = null)
    {
        if (is_array($productoId)) {
            $useMinMax = false;
            if (isset($productoId['min'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::PRODUCTO_ID, $productoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($productoId['max'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::PRODUCTO_ID, $productoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ProductoUbicacionPeer::PRODUCTO_ID, $productoId, $comparison);
    }

    /**
     * Filter the query on the cantidad column
     *
     * Example usage:
     * <code>
     * $query->filterByCantidad(1234); // WHERE cantidad = 1234
     * $query->filterByCantidad(array(12, 34)); // WHERE cantidad IN (12, 34)
     * $query->filterByCantidad(array('min' => 12)); // WHERE cantidad > 12
     * </code>
     *
     * @param     mixed $cantidad The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByCantidad($cantidad = null, $comparison = null)
    {
        if (is_array($cantidad)) {
            $useMinMax = false;
            if (isset($cantidad['min'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::CANTIDAD, $cantidad['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($cantidad['max'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::CANTIDAD, $cantidad['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ProductoUbicacionPeer::CANTIDAD, $cantidad, $comparison);
    }

    /**
     * Filter the query on the tienda_id column
     *
     * Example usage:
     * <code>
     * $query->filterByTiendaId(1234); // WHERE tienda_id = 1234
     * $query->filterByTiendaId(array(12, 34)); // WHERE tienda_id IN (12, 34)
     * $query->filterByTiendaId(array('min' => 12)); // WHERE tienda_id > 12
     * </code>
     *
     * @see       filterByTienda()
     *
     * @param     mixed $tiendaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByTiendaId($tiendaId = null, $comparison = null)
    {
        if (is_array($tiendaId)) {
            $useMinMax = false;
            if (isset($tiendaId['min'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::TIENDA_ID, $tiendaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($tiendaId['max'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::TIENDA_ID, $tiendaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ProductoUbicacionPeer::TIENDA_ID, $tiendaId, $comparison);
    }

    /**
     * Filter the query on the ubicacion column
     *
     * Example usage:
     * <code>
     * $query->filterByUbicacion('fooValue');   // WHERE ubicacion = 'fooValue'
     * $query->filterByUbicacion('%fooValue%'); // WHERE ubicacion LIKE '%fooValue%'
     * </code>
     *
     * @param     string $ubicacion The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByUbicacion($ubicacion = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($ubicacion)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $ubicacion)) {
                $ubicacion = str_replace('*', '%', $ubicacion);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ProductoUbicacionPeer::UBICACION, $ubicacion, $comparison);
    }

    /**
     * Filter the query on the transito column
     *
     * Example usage:
     * <code>
     * $query->filterByTransito(1234); // WHERE transito = 1234
     * $query->filterByTransito(array(12, 34)); // WHERE transito IN (12, 34)
     * $query->filterByTransito(array('min' => 12)); // WHERE transito > 12
     * </code>
     *
     * @param     mixed $transito The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function filterByTransito($transito = null, $comparison = null)
    {
        if (is_array($transito)) {
            $useMinMax = false;
            if (isset($transito['min'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::TRANSITO, $transito['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($transito['max'])) {
                $this->addUsingAlias(ProductoUbicacionPeer::TRANSITO, $transito['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ProductoUbicacionPeer::TRANSITO, $transito, $comparison);
    }

    /**
     * Filter the query by a related Empresa object
     *
     * @param   Empresa|PropelObjectCollection $empresa The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   ProductoUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByEmpresa($empresa, $comparison = null)
    {
        if ($empresa instanceof Empresa) {
            return $this
                ->addUsingAlias(ProductoUbicacionPeer::EMPRESA_ID, $empresa->getId(), $comparison);
        } elseif ($empresa instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ProductoUbicacionPeer::EMPRESA_ID, $empresa->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByEmpresa() only accepts arguments of type Empresa or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Empresa relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function joinEmpresa($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Empresa');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Empresa');
        }

        return $this;
    }

    /**
     * Use the Empresa relation Empresa object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   EmpresaQuery A secondary query class using the current class as primary query
     */
    public function useEmpresaQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinEmpresa($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Empresa', 'EmpresaQuery');
    }

    /**
     * Filter the query by a related Producto object
     *
     * @param   Producto|PropelObjectCollection $producto The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   ProductoUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByProducto($producto, $comparison = null)
    {
        if ($producto instanceof Producto) {
            return $this
                ->addUsingAlias(ProductoUbicacionPeer::PRODUCTO_ID, $producto->getId(), $comparison);
        } elseif ($producto instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ProductoUbicacionPeer::PRODUCTO_ID, $producto->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByProducto() only accepts arguments of type Producto or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Producto relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function joinProducto($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Producto');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Producto');
        }

        return $this;
    }

    /**
     * Use the Producto relation Producto object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ProductoQuery A secondary query class using the current class as primary query
     */
    public function useProductoQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinProducto($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Producto', 'ProductoQuery');
    }

    /**
     * Filter the query by a related Tienda object
     *
     * @param   Tienda|PropelObjectCollection $tienda The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   ProductoUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTienda($tienda, $comparison = null)
    {
        if ($tienda instanceof Tienda) {
            return $this
                ->addUsingAlias(ProductoUbicacionPeer::TIENDA_ID, $tienda->getId(), $comparison);
        } elseif ($tienda instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ProductoUbicacionPeer::TIENDA_ID, $tienda->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByTienda() only accepts arguments of type Tienda or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tienda relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function joinTienda($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tienda');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tienda');
        }

        return $this;
    }

    /**
     * Use the Tienda relation Tienda object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TiendaQuery A secondary query class using the current class as primary query
     */
    public function useTiendaQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinTienda($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tienda', 'TiendaQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   ProductoUbicacion $productoUbicacion Object to remove from the list of results
     *
     * @return ProductoUbicacionQuery The current query, for fluid interface
     */
    public function prune($productoUbicacion = null)
    {
        if ($productoUbicacion) {
            $this->addUsingAlias(ProductoUbicacionPeer::ID, $productoUbicacion->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
