<?php


/**
 * Base class that represents a row from the 'gasto_caja' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 01/03/26 04:09:44
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseGastoCaja extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'GastoCajaPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        GastoCajaPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the tienda_id field.
     * @var        int
     */
    protected $tienda_id;

    /**
     * The value for the empresa_id field.
     * @var        int
     */
    protected $empresa_id;

    /**
     * The value for the fecha field.
     * @var        string
     */
    protected $fecha;

    /**
     * The value for the concepto field.
     * @var        string
     */
    protected $concepto;

    /**
     * The value for the usuario field.
     * @var        string
     */
    protected $usuario;

    /**
     * The value for the created_at field.
     * @var        string
     */
    protected $created_at;

    /**
     * The value for the estatus field.
     * @var        string
     */
    protected $estatus;

    /**
     * The value for the gasto_id field.
     * @var        int
     */
    protected $gasto_id;

    /**
     * The value for the valor field.
     * @var        double
     */
    protected $valor;

    /**
     * The value for the observaciones field.
     * @var        string
     */
    protected $observaciones;

    /**
     * The value for the cuenta field.
     * @var        string
     */
    protected $cuenta;

    /**
     * The value for the partida_no field.
     * Note: this column has a database default value of: 0
     * @var        int
     */
    protected $partida_no;

    /**
     * @var        Tienda
     */
    protected $aTienda;

    /**
     * @var        Empresa
     */
    protected $aEmpresa;

    /**
     * @var        Gasto
     */
    protected $aGasto;

    /**
     * @var        PropelObjectCollection|GastoCajaDetalle[] Collection to store aggregation of GastoCajaDetalle objects.
     */
    protected $collGastoCajaDetalles;
    protected $collGastoCajaDetallesPartial;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $gastoCajaDetallesScheduledForDeletion = null;

    /**
     * Applies default values to this object.
     * This method should be called from the object's constructor (or
     * equivalent initialization method).
     * @see        __construct()
     */
    public function applyDefaultValues()
    {
        $this->partida_no = 0;
    }

    /**
     * Initializes internal state of BaseGastoCaja object.
     * @see        applyDefaults()
     */
    public function __construct()
    {
        parent::__construct();
        $this->applyDefaultValues();
    }

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [tienda_id] column value.
     *
     * @return int
     */
    public function getTiendaId()
    {
        return $this->tienda_id;
    }

    /**
     * Get the [empresa_id] column value.
     *
     * @return int
     */
    public function getEmpresaId()
    {
        return $this->empresa_id;
    }

    /**
     * Get the [optionally formatted] temporal [fecha] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getFecha($format = 'Y-m-d')
    {
        if ($this->fecha === null) {
            return null;
        }

        if ($this->fecha === '0000-00-00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->fecha);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [concepto] column value.
     *
     * @return string
     */
    public function getConcepto()
    {
        return $this->concepto;
    }

    /**
     * Get the [usuario] column value.
     *
     * @return string
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    /**
     * Get the [optionally formatted] temporal [created_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getCreatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->created_at === null) {
            return null;
        }

        if ($this->created_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->created_at);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [estatus] column value.
     *
     * @return string
     */
    public function getEstatus()
    {
        return $this->estatus;
    }

    /**
     * Get the [gasto_id] column value.
     *
     * @return int
     */
    public function getGastoId()
    {
        return $this->gasto_id;
    }

    /**
     * Get the [valor] column value.
     *
     * @return double
     */
    public function getValor()
    {
        return $this->valor;
    }

    /**
     * Get the [observaciones] column value.
     *
     * @return string
     */
    public function getObservaciones()
    {
        return $this->observaciones;
    }

    /**
     * Get the [cuenta] column value.
     *
     * @return string
     */
    public function getCuenta()
    {
        return $this->cuenta;
    }

    /**
     * Get the [partida_no] column value.
     *
     * @return int
     */
    public function getPartidaNo()
    {
        return $this->partida_no;
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = GastoCajaPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [tienda_id] column.
     *
     * @param int $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setTiendaId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->tienda_id !== $v) {
            $this->tienda_id = $v;
            $this->modifiedColumns[] = GastoCajaPeer::TIENDA_ID;
        }

        if ($this->aTienda !== null && $this->aTienda->getId() !== $v) {
            $this->aTienda = null;
        }


        return $this;
    } // setTiendaId()

    /**
     * Set the value of [empresa_id] column.
     *
     * @param int $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setEmpresaId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->empresa_id !== $v) {
            $this->empresa_id = $v;
            $this->modifiedColumns[] = GastoCajaPeer::EMPRESA_ID;
        }

        if ($this->aEmpresa !== null && $this->aEmpresa->getId() !== $v) {
            $this->aEmpresa = null;
        }


        return $this;
    } // setEmpresaId()

    /**
     * Sets the value of [fecha] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setFecha($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->fecha !== null || $dt !== null) {
            $currentDateAsString = ($this->fecha !== null && $tmpDt = new DateTime($this->fecha)) ? $tmpDt->format('Y-m-d') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->fecha = $newDateAsString;
                $this->modifiedColumns[] = GastoCajaPeer::FECHA;
            }
        } // if either are not null


        return $this;
    } // setFecha()

    /**
     * Set the value of [concepto] column.
     *
     * @param string $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setConcepto($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->concepto !== $v) {
            $this->concepto = $v;
            $this->modifiedColumns[] = GastoCajaPeer::CONCEPTO;
        }


        return $this;
    } // setConcepto()

    /**
     * Set the value of [usuario] column.
     *
     * @param string $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setUsuario($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->usuario !== $v) {
            $this->usuario = $v;
            $this->modifiedColumns[] = GastoCajaPeer::USUARIO;
        }


        return $this;
    } // setUsuario()

    /**
     * Sets the value of [created_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setCreatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->created_at !== null || $dt !== null) {
            $currentDateAsString = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->created_at = $newDateAsString;
                $this->modifiedColumns[] = GastoCajaPeer::CREATED_AT;
            }
        } // if either are not null


        return $this;
    } // setCreatedAt()

    /**
     * Set the value of [estatus] column.
     *
     * @param string $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setEstatus($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->estatus !== $v) {
            $this->estatus = $v;
            $this->modifiedColumns[] = GastoCajaPeer::ESTATUS;
        }


        return $this;
    } // setEstatus()

    /**
     * Set the value of [gasto_id] column.
     *
     * @param int $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setGastoId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->gasto_id !== $v) {
            $this->gasto_id = $v;
            $this->modifiedColumns[] = GastoCajaPeer::GASTO_ID;
        }

        if ($this->aGasto !== null && $this->aGasto->getId() !== $v) {
            $this->aGasto = null;
        }


        return $this;
    } // setGastoId()

    /**
     * Set the value of [valor] column.
     *
     * @param double $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setValor($v)
    {
        if ($v !== null) {
            $v = (double) $v;
        }

        if ($this->valor !== $v) {
            $this->valor = $v;
            $this->modifiedColumns[] = GastoCajaPeer::VALOR;
        }


        return $this;
    } // setValor()

    /**
     * Set the value of [observaciones] column.
     *
     * @param string $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setObservaciones($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->observaciones !== $v) {
            $this->observaciones = $v;
            $this->modifiedColumns[] = GastoCajaPeer::OBSERVACIONES;
        }


        return $this;
    } // setObservaciones()

    /**
     * Set the value of [cuenta] column.
     *
     * @param string $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setCuenta($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->cuenta !== $v) {
            $this->cuenta = $v;
            $this->modifiedColumns[] = GastoCajaPeer::CUENTA;
        }


        return $this;
    } // setCuenta()

    /**
     * Set the value of [partida_no] column.
     *
     * @param int $v new value
     * @return GastoCaja The current object (for fluent API support)
     */
    public function setPartidaNo($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->partida_no !== $v) {
            $this->partida_no = $v;
            $this->modifiedColumns[] = GastoCajaPeer::PARTIDA_NO;
        }


        return $this;
    } // setPartidaNo()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
            if ($this->partida_no !== 0) {
                return false;
            }

        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->tienda_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
            $this->empresa_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
            $this->fecha = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->concepto = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
            $this->usuario = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
            $this->created_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
            $this->estatus = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
            $this->gasto_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
            $this->valor = ($row[$startcol + 9] !== null) ? (double) $row[$startcol + 9] : null;
            $this->observaciones = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
            $this->cuenta = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
            $this->partida_no = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 13; // 13 = GastoCajaPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating GastoCaja object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

        if ($this->aTienda !== null && $this->tienda_id !== $this->aTienda->getId()) {
            $this->aTienda = null;
        }
        if ($this->aEmpresa !== null && $this->empresa_id !== $this->aEmpresa->getId()) {
            $this->aEmpresa = null;
        }
        if ($this->aGasto !== null && $this->gasto_id !== $this->aGasto->getId()) {
            $this->aGasto = null;
        }
    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(GastoCajaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = GastoCajaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->aTienda = null;
            $this->aEmpresa = null;
            $this->aGasto = null;
            $this->collGastoCajaDetalles = null;

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(GastoCajaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = GastoCajaQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseGastoCaja:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseGastoCaja:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(GastoCajaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseGastoCaja:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
                // symfony_timestampable behavior
                if (!$this->isColumnModified(GastoCajaPeer::CREATED_AT))
                {
                  $this->setCreatedAt(time());
                }

            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseGastoCaja:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                GastoCajaPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            // We call the save method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aTienda !== null) {
                if ($this->aTienda->isModified() || $this->aTienda->isNew()) {
                    $affectedRows += $this->aTienda->save($con);
                }
                $this->setTienda($this->aTienda);
            }

            if ($this->aEmpresa !== null) {
                if ($this->aEmpresa->isModified() || $this->aEmpresa->isNew()) {
                    $affectedRows += $this->aEmpresa->save($con);
                }
                $this->setEmpresa($this->aEmpresa);
            }

            if ($this->aGasto !== null) {
                if ($this->aGasto->isModified() || $this->aGasto->isNew()) {
                    $affectedRows += $this->aGasto->save($con);
                }
                $this->setGasto($this->aGasto);
            }

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            if ($this->gastoCajaDetallesScheduledForDeletion !== null) {
                if (!$this->gastoCajaDetallesScheduledForDeletion->isEmpty()) {
                    foreach ($this->gastoCajaDetallesScheduledForDeletion as $gastoCajaDetalle) {
                        // need to save related object because we set the relation to null
                        $gastoCajaDetalle->save($con);
                    }
                    $this->gastoCajaDetallesScheduledForDeletion = null;
                }
            }

            if ($this->collGastoCajaDetalles !== null) {
                foreach ($this->collGastoCajaDetalles as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = GastoCajaPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . GastoCajaPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(GastoCajaPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(GastoCajaPeer::TIENDA_ID)) {
            $modifiedColumns[':p' . $index++]  = '`TIENDA_ID`';
        }
        if ($this->isColumnModified(GastoCajaPeer::EMPRESA_ID)) {
            $modifiedColumns[':p' . $index++]  = '`EMPRESA_ID`';
        }
        if ($this->isColumnModified(GastoCajaPeer::FECHA)) {
            $modifiedColumns[':p' . $index++]  = '`FECHA`';
        }
        if ($this->isColumnModified(GastoCajaPeer::CONCEPTO)) {
            $modifiedColumns[':p' . $index++]  = '`CONCEPTO`';
        }
        if ($this->isColumnModified(GastoCajaPeer::USUARIO)) {
            $modifiedColumns[':p' . $index++]  = '`USUARIO`';
        }
        if ($this->isColumnModified(GastoCajaPeer::CREATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`CREATED_AT`';
        }
        if ($this->isColumnModified(GastoCajaPeer::ESTATUS)) {
            $modifiedColumns[':p' . $index++]  = '`ESTATUS`';
        }
        if ($this->isColumnModified(GastoCajaPeer::GASTO_ID)) {
            $modifiedColumns[':p' . $index++]  = '`GASTO_ID`';
        }
        if ($this->isColumnModified(GastoCajaPeer::VALOR)) {
            $modifiedColumns[':p' . $index++]  = '`VALOR`';
        }
        if ($this->isColumnModified(GastoCajaPeer::OBSERVACIONES)) {
            $modifiedColumns[':p' . $index++]  = '`OBSERVACIONES`';
        }
        if ($this->isColumnModified(GastoCajaPeer::CUENTA)) {
            $modifiedColumns[':p' . $index++]  = '`CUENTA`';
        }
        if ($this->isColumnModified(GastoCajaPeer::PARTIDA_NO)) {
            $modifiedColumns[':p' . $index++]  = '`PARTIDA_NO`';
        }

        $sql = sprintf(
            'INSERT INTO `gasto_caja` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`TIENDA_ID`':
                        $stmt->bindValue($identifier, $this->tienda_id, PDO::PARAM_INT);
                        break;
                    case '`EMPRESA_ID`':
                        $stmt->bindValue($identifier, $this->empresa_id, PDO::PARAM_INT);
                        break;
                    case '`FECHA`':
                        $stmt->bindValue($identifier, $this->fecha, PDO::PARAM_STR);
                        break;
                    case '`CONCEPTO`':
                        $stmt->bindValue($identifier, $this->concepto, PDO::PARAM_STR);
                        break;
                    case '`USUARIO`':
                        $stmt->bindValue($identifier, $this->usuario, PDO::PARAM_STR);
                        break;
                    case '`CREATED_AT`':
                        $stmt->bindValue($identifier, $this->created_at, PDO::PARAM_STR);
                        break;
                    case '`ESTATUS`':
                        $stmt->bindValue($identifier, $this->estatus, PDO::PARAM_STR);
                        break;
                    case '`GASTO_ID`':
                        $stmt->bindValue($identifier, $this->gasto_id, PDO::PARAM_INT);
                        break;
                    case '`VALOR`':
                        $stmt->bindValue($identifier, $this->valor, PDO::PARAM_STR);
                        break;
                    case '`OBSERVACIONES`':
                        $stmt->bindValue($identifier, $this->observaciones, PDO::PARAM_STR);
                        break;
                    case '`CUENTA`':
                        $stmt->bindValue($identifier, $this->cuenta, PDO::PARAM_STR);
                        break;
                    case '`PARTIDA_NO`':
                        $stmt->bindValue($identifier, $this->partida_no, PDO::PARAM_INT);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            // We call the validate method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aTienda !== null) {
                if (!$this->aTienda->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aTienda->getValidationFailures());
                }
            }

            if ($this->aEmpresa !== null) {
                if (!$this->aEmpresa->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aEmpresa->getValidationFailures());
                }
            }

            if ($this->aGasto !== null) {
                if (!$this->aGasto->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aGasto->getValidationFailures());
                }
            }


            if (($retval = GastoCajaPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }


                if ($this->collGastoCajaDetalles !== null) {
                    foreach ($this->collGastoCajaDetalles as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }


            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = GastoCajaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getTiendaId();
                break;
            case 2:
                return $this->getEmpresaId();
                break;
            case 3:
                return $this->getFecha();
                break;
            case 4:
                return $this->getConcepto();
                break;
            case 5:
                return $this->getUsuario();
                break;
            case 6:
                return $this->getCreatedAt();
                break;
            case 7:
                return $this->getEstatus();
                break;
            case 8:
                return $this->getGastoId();
                break;
            case 9:
                return $this->getValor();
                break;
            case 10:
                return $this->getObservaciones();
                break;
            case 11:
                return $this->getCuenta();
                break;
            case 12:
                return $this->getPartidaNo();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['GastoCaja'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['GastoCaja'][$this->getPrimaryKey()] = true;
        $keys = GastoCajaPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getTiendaId(),
            $keys[2] => $this->getEmpresaId(),
            $keys[3] => $this->getFecha(),
            $keys[4] => $this->getConcepto(),
            $keys[5] => $this->getUsuario(),
            $keys[6] => $this->getCreatedAt(),
            $keys[7] => $this->getEstatus(),
            $keys[8] => $this->getGastoId(),
            $keys[9] => $this->getValor(),
            $keys[10] => $this->getObservaciones(),
            $keys[11] => $this->getCuenta(),
            $keys[12] => $this->getPartidaNo(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->aTienda) {
                $result['Tienda'] = $this->aTienda->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->aEmpresa) {
                $result['Empresa'] = $this->aEmpresa->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->aGasto) {
                $result['Gasto'] = $this->aGasto->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->collGastoCajaDetalles) {
                $result['GastoCajaDetalles'] = $this->collGastoCajaDetalles->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = GastoCajaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setTiendaId($value);
                break;
            case 2:
                $this->setEmpresaId($value);
                break;
            case 3:
                $this->setFecha($value);
                break;
            case 4:
                $this->setConcepto($value);
                break;
            case 5:
                $this->setUsuario($value);
                break;
            case 6:
                $this->setCreatedAt($value);
                break;
            case 7:
                $this->setEstatus($value);
                break;
            case 8:
                $this->setGastoId($value);
                break;
            case 9:
                $this->setValor($value);
                break;
            case 10:
                $this->setObservaciones($value);
                break;
            case 11:
                $this->setCuenta($value);
                break;
            case 12:
                $this->setPartidaNo($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = GastoCajaPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setTiendaId($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setEmpresaId($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setFecha($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setConcepto($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setUsuario($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setCreatedAt($arr[$keys[6]]);
        if (array_key_exists($keys[7], $arr)) $this->setEstatus($arr[$keys[7]]);
        if (array_key_exists($keys[8], $arr)) $this->setGastoId($arr[$keys[8]]);
        if (array_key_exists($keys[9], $arr)) $this->setValor($arr[$keys[9]]);
        if (array_key_exists($keys[10], $arr)) $this->setObservaciones($arr[$keys[10]]);
        if (array_key_exists($keys[11], $arr)) $this->setCuenta($arr[$keys[11]]);
        if (array_key_exists($keys[12], $arr)) $this->setPartidaNo($arr[$keys[12]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(GastoCajaPeer::DATABASE_NAME);

        if ($this->isColumnModified(GastoCajaPeer::ID)) $criteria->add(GastoCajaPeer::ID, $this->id);
        if ($this->isColumnModified(GastoCajaPeer::TIENDA_ID)) $criteria->add(GastoCajaPeer::TIENDA_ID, $this->tienda_id);
        if ($this->isColumnModified(GastoCajaPeer::EMPRESA_ID)) $criteria->add(GastoCajaPeer::EMPRESA_ID, $this->empresa_id);
        if ($this->isColumnModified(GastoCajaPeer::FECHA)) $criteria->add(GastoCajaPeer::FECHA, $this->fecha);
        if ($this->isColumnModified(GastoCajaPeer::CONCEPTO)) $criteria->add(GastoCajaPeer::CONCEPTO, $this->concepto);
        if ($this->isColumnModified(GastoCajaPeer::USUARIO)) $criteria->add(GastoCajaPeer::USUARIO, $this->usuario);
        if ($this->isColumnModified(GastoCajaPeer::CREATED_AT)) $criteria->add(GastoCajaPeer::CREATED_AT, $this->created_at);
        if ($this->isColumnModified(GastoCajaPeer::ESTATUS)) $criteria->add(GastoCajaPeer::ESTATUS, $this->estatus);
        if ($this->isColumnModified(GastoCajaPeer::GASTO_ID)) $criteria->add(GastoCajaPeer::GASTO_ID, $this->gasto_id);
        if ($this->isColumnModified(GastoCajaPeer::VALOR)) $criteria->add(GastoCajaPeer::VALOR, $this->valor);
        if ($this->isColumnModified(GastoCajaPeer::OBSERVACIONES)) $criteria->add(GastoCajaPeer::OBSERVACIONES, $this->observaciones);
        if ($this->isColumnModified(GastoCajaPeer::CUENTA)) $criteria->add(GastoCajaPeer::CUENTA, $this->cuenta);
        if ($this->isColumnModified(GastoCajaPeer::PARTIDA_NO)) $criteria->add(GastoCajaPeer::PARTIDA_NO, $this->partida_no);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(GastoCajaPeer::DATABASE_NAME);
        $criteria->add(GastoCajaPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of GastoCaja (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setTiendaId($this->getTiendaId());
        $copyObj->setEmpresaId($this->getEmpresaId());
        $copyObj->setFecha($this->getFecha());
        $copyObj->setConcepto($this->getConcepto());
        $copyObj->setUsuario($this->getUsuario());
        $copyObj->setCreatedAt($this->getCreatedAt());
        $copyObj->setEstatus($this->getEstatus());
        $copyObj->setGastoId($this->getGastoId());
        $copyObj->setValor($this->getValor());
        $copyObj->setObservaciones($this->getObservaciones());
        $copyObj->setCuenta($this->getCuenta());
        $copyObj->setPartidaNo($this->getPartidaNo());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            foreach ($this->getGastoCajaDetalles() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addGastoCajaDetalle($relObj->copy($deepCopy));
                }
            }

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return GastoCaja Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return GastoCajaPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new GastoCajaPeer();
        }

        return self::$peer;
    }

    /**
     * Declares an association between this object and a Tienda object.
     *
     * @param             Tienda $v
     * @return GastoCaja The current object (for fluent API support)
     * @throws PropelException
     */
    public function setTienda(Tienda $v = null)
    {
        if ($v === null) {
            $this->setTiendaId(NULL);
        } else {
            $this->setTiendaId($v->getId());
        }

        $this->aTienda = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Tienda object, it will not be re-added.
        if ($v !== null) {
            $v->addGastoCaja($this);
        }


        return $this;
    }


    /**
     * Get the associated Tienda object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Tienda The associated Tienda object.
     * @throws PropelException
     */
    public function getTienda(PropelPDO $con = null)
    {
        if ($this->aTienda === null && ($this->tienda_id !== null)) {
            $this->aTienda = TiendaQuery::create()->findPk($this->tienda_id, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aTienda->addGastoCajas($this);
             */
        }

        return $this->aTienda;
    }

    /**
     * Declares an association between this object and a Empresa object.
     *
     * @param             Empresa $v
     * @return GastoCaja The current object (for fluent API support)
     * @throws PropelException
     */
    public function setEmpresa(Empresa $v = null)
    {
        if ($v === null) {
            $this->setEmpresaId(NULL);
        } else {
            $this->setEmpresaId($v->getId());
        }

        $this->aEmpresa = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Empresa object, it will not be re-added.
        if ($v !== null) {
            $v->addGastoCaja($this);
        }


        return $this;
    }


    /**
     * Get the associated Empresa object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Empresa The associated Empresa object.
     * @throws PropelException
     */
    public function getEmpresa(PropelPDO $con = null)
    {
        if ($this->aEmpresa === null && ($this->empresa_id !== null)) {
            $this->aEmpresa = EmpresaQuery::create()->findPk($this->empresa_id, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aEmpresa->addGastoCajas($this);
             */
        }

        return $this->aEmpresa;
    }

    /**
     * Declares an association between this object and a Gasto object.
     *
     * @param             Gasto $v
     * @return GastoCaja The current object (for fluent API support)
     * @throws PropelException
     */
    public function setGasto(Gasto $v = null)
    {
        if ($v === null) {
            $this->setGastoId(NULL);
        } else {
            $this->setGastoId($v->getId());
        }

        $this->aGasto = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Gasto object, it will not be re-added.
        if ($v !== null) {
            $v->addGastoCaja($this);
        }


        return $this;
    }


    /**
     * Get the associated Gasto object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Gasto The associated Gasto object.
     * @throws PropelException
     */
    public function getGasto(PropelPDO $con = null)
    {
        if ($this->aGasto === null && ($this->gasto_id !== null)) {
            $this->aGasto = GastoQuery::create()->findPk($this->gasto_id, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aGasto->addGastoCajas($this);
             */
        }

        return $this->aGasto;
    }


    /**
     * Initializes a collection based on the name of a relation.
     * Avoids crafting an 'init[$relationName]s' method name
     * that wouldn't work when StandardEnglishPluralizer is used.
     *
     * @param string $relationName The name of the relation to initialize
     * @return void
     */
    public function initRelation($relationName)
    {
        if ('GastoCajaDetalle' == $relationName) {
            $this->initGastoCajaDetalles();
        }
    }

    /**
     * Clears out the collGastoCajaDetalles collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addGastoCajaDetalles()
     */
    public function clearGastoCajaDetalles()
    {
        $this->collGastoCajaDetalles = null; // important to set this to null since that means it is uninitialized
        $this->collGastoCajaDetallesPartial = null;
    }

    /**
     * reset is the collGastoCajaDetalles collection loaded partially
     *
     * @return void
     */
    public function resetPartialGastoCajaDetalles($v = true)
    {
        $this->collGastoCajaDetallesPartial = $v;
    }

    /**
     * Initializes the collGastoCajaDetalles collection.
     *
     * By default this just sets the collGastoCajaDetalles collection to an empty array (like clearcollGastoCajaDetalles());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initGastoCajaDetalles($overrideExisting = true)
    {
        if (null !== $this->collGastoCajaDetalles && !$overrideExisting) {
            return;
        }
        $this->collGastoCajaDetalles = new PropelObjectCollection();
        $this->collGastoCajaDetalles->setModel('GastoCajaDetalle');
    }

    /**
     * Gets an array of GastoCajaDetalle objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this GastoCaja is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|GastoCajaDetalle[] List of GastoCajaDetalle objects
     * @throws PropelException
     */
    public function getGastoCajaDetalles($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collGastoCajaDetallesPartial && !$this->isNew();
        if (null === $this->collGastoCajaDetalles || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collGastoCajaDetalles) {
                // return empty collection
                $this->initGastoCajaDetalles();
            } else {
                $collGastoCajaDetalles = GastoCajaDetalleQuery::create(null, $criteria)
                    ->filterByGastoCaja($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collGastoCajaDetallesPartial && count($collGastoCajaDetalles)) {
                      $this->initGastoCajaDetalles(false);

                      foreach($collGastoCajaDetalles as $obj) {
                        if (false == $this->collGastoCajaDetalles->contains($obj)) {
                          $this->collGastoCajaDetalles->append($obj);
                        }
                      }

                      $this->collGastoCajaDetallesPartial = true;
                    }

                    return $collGastoCajaDetalles;
                }

                if($partial && $this->collGastoCajaDetalles) {
                    foreach($this->collGastoCajaDetalles as $obj) {
                        if($obj->isNew()) {
                            $collGastoCajaDetalles[] = $obj;
                        }
                    }
                }

                $this->collGastoCajaDetalles = $collGastoCajaDetalles;
                $this->collGastoCajaDetallesPartial = false;
            }
        }

        return $this->collGastoCajaDetalles;
    }

    /**
     * Sets a collection of GastoCajaDetalle objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $gastoCajaDetalles A Propel collection.
     * @param PropelPDO $con Optional connection object
     */
    public function setGastoCajaDetalles(PropelCollection $gastoCajaDetalles, PropelPDO $con = null)
    {
        $this->gastoCajaDetallesScheduledForDeletion = $this->getGastoCajaDetalles(new Criteria(), $con)->diff($gastoCajaDetalles);

        foreach ($this->gastoCajaDetallesScheduledForDeletion as $gastoCajaDetalleRemoved) {
            $gastoCajaDetalleRemoved->setGastoCaja(null);
        }

        $this->collGastoCajaDetalles = null;
        foreach ($gastoCajaDetalles as $gastoCajaDetalle) {
            $this->addGastoCajaDetalle($gastoCajaDetalle);
        }

        $this->collGastoCajaDetalles = $gastoCajaDetalles;
        $this->collGastoCajaDetallesPartial = false;
    }

    /**
     * Returns the number of related GastoCajaDetalle objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related GastoCajaDetalle objects.
     * @throws PropelException
     */
    public function countGastoCajaDetalles(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collGastoCajaDetallesPartial && !$this->isNew();
        if (null === $this->collGastoCajaDetalles || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collGastoCajaDetalles) {
                return 0;
            } else {
                if($partial && !$criteria) {
                    return count($this->getGastoCajaDetalles());
                }
                $query = GastoCajaDetalleQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterByGastoCaja($this)
                    ->count($con);
            }
        } else {
            return count($this->collGastoCajaDetalles);
        }
    }

    /**
     * Method called to associate a GastoCajaDetalle object to this object
     * through the GastoCajaDetalle foreign key attribute.
     *
     * @param    GastoCajaDetalle $l GastoCajaDetalle
     * @return GastoCaja The current object (for fluent API support)
     */
    public function addGastoCajaDetalle(GastoCajaDetalle $l)
    {
        if ($this->collGastoCajaDetalles === null) {
            $this->initGastoCajaDetalles();
            $this->collGastoCajaDetallesPartial = true;
        }
        if (!$this->collGastoCajaDetalles->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddGastoCajaDetalle($l);
        }

        return $this;
    }

    /**
     * @param	GastoCajaDetalle $gastoCajaDetalle The gastoCajaDetalle object to add.
     */
    protected function doAddGastoCajaDetalle($gastoCajaDetalle)
    {
        $this->collGastoCajaDetalles[]= $gastoCajaDetalle;
        $gastoCajaDetalle->setGastoCaja($this);
    }

    /**
     * @param	GastoCajaDetalle $gastoCajaDetalle The gastoCajaDetalle object to remove.
     */
    public function removeGastoCajaDetalle($gastoCajaDetalle)
    {
        if ($this->getGastoCajaDetalles()->contains($gastoCajaDetalle)) {
            $this->collGastoCajaDetalles->remove($this->collGastoCajaDetalles->search($gastoCajaDetalle));
            if (null === $this->gastoCajaDetallesScheduledForDeletion) {
                $this->gastoCajaDetallesScheduledForDeletion = clone $this->collGastoCajaDetalles;
                $this->gastoCajaDetallesScheduledForDeletion->clear();
            }
            $this->gastoCajaDetallesScheduledForDeletion[]= $gastoCajaDetalle;
            $gastoCajaDetalle->setGastoCaja(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this GastoCaja is new, it will return
     * an empty collection; or if this GastoCaja has previously
     * been saved, it will retrieve related GastoCajaDetalles from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in GastoCaja.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|GastoCajaDetalle[] List of GastoCajaDetalle objects
     */
    public function getGastoCajaDetallesJoinProveedor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = GastoCajaDetalleQuery::create(null, $criteria);
        $query->joinWith('Proveedor', $join_behavior);

        return $this->getGastoCajaDetalles($query, $con);
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->tienda_id = null;
        $this->empresa_id = null;
        $this->fecha = null;
        $this->concepto = null;
        $this->usuario = null;
        $this->created_at = null;
        $this->estatus = null;
        $this->gasto_id = null;
        $this->valor = null;
        $this->observaciones = null;
        $this->cuenta = null;
        $this->partida_no = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->applyDefaultValues();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
            if ($this->collGastoCajaDetalles) {
                foreach ($this->collGastoCajaDetalles as $o) {
                    $o->clearAllReferences($deep);
                }
            }
        } // if ($deep)

        if ($this->collGastoCajaDetalles instanceof PropelCollection) {
            $this->collGastoCajaDetalles->clearIterator();
        }
        $this->collGastoCajaDetalles = null;
        $this->aTienda = null;
        $this->aEmpresa = null;
        $this->aGasto = null;
    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(GastoCajaPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {

        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BaseGastoCaja:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
