<?php


/**
 * Base class that represents a query for the 'ingreso_producto' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/30/25 22:58:30
 *
 * @method IngresoProductoQuery orderById($order = Criteria::ASC) Order by the id column
 * @method IngresoProductoQuery orderByUsuarioId($order = Criteria::ASC) Order by the usuario_id column
 * @method IngresoProductoQuery orderByFecha($order = Criteria::ASC) Order by the fecha column
 * @method IngresoProductoQuery orderByTiendaId($order = Criteria::ASC) Order by the tienda_id column
 * @method IngresoProductoQuery orderByEmpresaId($order = Criteria::ASC) Order by the empresa_id column
 * @method IngresoProductoQuery orderByFechaDocumento($order = Criteria::ASC) Order by the fecha_documento column
 * @method IngresoProductoQuery orderByObservaciones($order = Criteria::ASC) Order by the observaciones column
 * @method IngresoProductoQuery orderByNumeroDocumento($order = Criteria::ASC) Order by the numero_documento column
 * @method IngresoProductoQuery orderByNumeroOrden($order = Criteria::ASC) Order by the numero_orden column
 *
 * @method IngresoProductoQuery groupById() Group by the id column
 * @method IngresoProductoQuery groupByUsuarioId() Group by the usuario_id column
 * @method IngresoProductoQuery groupByFecha() Group by the fecha column
 * @method IngresoProductoQuery groupByTiendaId() Group by the tienda_id column
 * @method IngresoProductoQuery groupByEmpresaId() Group by the empresa_id column
 * @method IngresoProductoQuery groupByFechaDocumento() Group by the fecha_documento column
 * @method IngresoProductoQuery groupByObservaciones() Group by the observaciones column
 * @method IngresoProductoQuery groupByNumeroDocumento() Group by the numero_documento column
 * @method IngresoProductoQuery groupByNumeroOrden() Group by the numero_orden column
 *
 * @method IngresoProductoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method IngresoProductoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method IngresoProductoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method IngresoProductoQuery leftJoinUsuario($relationAlias = null) Adds a LEFT JOIN clause to the query using the Usuario relation
 * @method IngresoProductoQuery rightJoinUsuario($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Usuario relation
 * @method IngresoProductoQuery innerJoinUsuario($relationAlias = null) Adds a INNER JOIN clause to the query using the Usuario relation
 *
 * @method IngresoProductoQuery leftJoinTienda($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tienda relation
 * @method IngresoProductoQuery rightJoinTienda($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tienda relation
 * @method IngresoProductoQuery innerJoinTienda($relationAlias = null) Adds a INNER JOIN clause to the query using the Tienda relation
 *
 * @method IngresoProductoQuery leftJoinEmpresa($relationAlias = null) Adds a LEFT JOIN clause to the query using the Empresa relation
 * @method IngresoProductoQuery rightJoinEmpresa($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Empresa relation
 * @method IngresoProductoQuery innerJoinEmpresa($relationAlias = null) Adds a INNER JOIN clause to the query using the Empresa relation
 *
 * @method IngresoProductoQuery leftJoinIngresoProductoDetalle($relationAlias = null) Adds a LEFT JOIN clause to the query using the IngresoProductoDetalle relation
 * @method IngresoProductoQuery rightJoinIngresoProductoDetalle($relationAlias = null) Adds a RIGHT JOIN clause to the query using the IngresoProductoDetalle relation
 * @method IngresoProductoQuery innerJoinIngresoProductoDetalle($relationAlias = null) Adds a INNER JOIN clause to the query using the IngresoProductoDetalle relation
 *
 * @method IngresoProductoQuery leftJoinInventarioVence($relationAlias = null) Adds a LEFT JOIN clause to the query using the InventarioVence relation
 * @method IngresoProductoQuery rightJoinInventarioVence($relationAlias = null) Adds a RIGHT JOIN clause to the query using the InventarioVence relation
 * @method IngresoProductoQuery innerJoinInventarioVence($relationAlias = null) Adds a INNER JOIN clause to the query using the InventarioVence relation
 *
 * @method IngresoProducto findOne(PropelPDO $con = null) Return the first IngresoProducto matching the query
 * @method IngresoProducto findOneOrCreate(PropelPDO $con = null) Return the first IngresoProducto matching the query, or a new IngresoProducto object populated from the query conditions when no match is found
 *
 * @method IngresoProducto findOneById(int $id) Return the first IngresoProducto filtered by the id column
 * @method IngresoProducto findOneByUsuarioId(int $usuario_id) Return the first IngresoProducto filtered by the usuario_id column
 * @method IngresoProducto findOneByFecha(string $fecha) Return the first IngresoProducto filtered by the fecha column
 * @method IngresoProducto findOneByTiendaId(int $tienda_id) Return the first IngresoProducto filtered by the tienda_id column
 * @method IngresoProducto findOneByEmpresaId(int $empresa_id) Return the first IngresoProducto filtered by the empresa_id column
 * @method IngresoProducto findOneByFechaDocumento(string $fecha_documento) Return the first IngresoProducto filtered by the fecha_documento column
 * @method IngresoProducto findOneByObservaciones(string $observaciones) Return the first IngresoProducto filtered by the observaciones column
 * @method IngresoProducto findOneByNumeroDocumento(string $numero_documento) Return the first IngresoProducto filtered by the numero_documento column
 * @method IngresoProducto findOneByNumeroOrden(string $numero_orden) Return the first IngresoProducto filtered by the numero_orden column
 *
 * @method array findById(int $id) Return IngresoProducto objects filtered by the id column
 * @method array findByUsuarioId(int $usuario_id) Return IngresoProducto objects filtered by the usuario_id column
 * @method array findByFecha(string $fecha) Return IngresoProducto objects filtered by the fecha column
 * @method array findByTiendaId(int $tienda_id) Return IngresoProducto objects filtered by the tienda_id column
 * @method array findByEmpresaId(int $empresa_id) Return IngresoProducto objects filtered by the empresa_id column
 * @method array findByFechaDocumento(string $fecha_documento) Return IngresoProducto objects filtered by the fecha_documento column
 * @method array findByObservaciones(string $observaciones) Return IngresoProducto objects filtered by the observaciones column
 * @method array findByNumeroDocumento(string $numero_documento) Return IngresoProducto objects filtered by the numero_documento column
 * @method array findByNumeroOrden(string $numero_orden) Return IngresoProducto objects filtered by the numero_orden column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseIngresoProductoQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseIngresoProductoQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'IngresoProducto', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new IngresoProductoQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     IngresoProductoQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return IngresoProductoQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof IngresoProductoQuery) {
            return $criteria;
        }
        $query = new IngresoProductoQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   IngresoProducto|IngresoProducto[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = IngresoProductoPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(IngresoProductoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   IngresoProducto A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `USUARIO_ID`, `FECHA`, `TIENDA_ID`, `EMPRESA_ID`, `FECHA_DOCUMENTO`, `OBSERVACIONES`, `NUMERO_DOCUMENTO`, `NUMERO_ORDEN` FROM `ingreso_producto` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new IngresoProducto();
            $obj->hydrate($row);
            IngresoProductoPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return IngresoProducto|IngresoProducto[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|IngresoProducto[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(IngresoProductoPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(IngresoProductoPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(IngresoProductoPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the usuario_id column
     *
     * Example usage:
     * <code>
     * $query->filterByUsuarioId(1234); // WHERE usuario_id = 1234
     * $query->filterByUsuarioId(array(12, 34)); // WHERE usuario_id IN (12, 34)
     * $query->filterByUsuarioId(array('min' => 12)); // WHERE usuario_id > 12
     * </code>
     *
     * @see       filterByUsuario()
     *
     * @param     mixed $usuarioId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByUsuarioId($usuarioId = null, $comparison = null)
    {
        if (is_array($usuarioId)) {
            $useMinMax = false;
            if (isset($usuarioId['min'])) {
                $this->addUsingAlias(IngresoProductoPeer::USUARIO_ID, $usuarioId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($usuarioId['max'])) {
                $this->addUsingAlias(IngresoProductoPeer::USUARIO_ID, $usuarioId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::USUARIO_ID, $usuarioId, $comparison);
    }

    /**
     * Filter the query on the fecha column
     *
     * Example usage:
     * <code>
     * $query->filterByFecha('2011-03-14'); // WHERE fecha = '2011-03-14'
     * $query->filterByFecha('now'); // WHERE fecha = '2011-03-14'
     * $query->filterByFecha(array('max' => 'yesterday')); // WHERE fecha > '2011-03-13'
     * </code>
     *
     * @param     mixed $fecha The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByFecha($fecha = null, $comparison = null)
    {
        if (is_array($fecha)) {
            $useMinMax = false;
            if (isset($fecha['min'])) {
                $this->addUsingAlias(IngresoProductoPeer::FECHA, $fecha['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($fecha['max'])) {
                $this->addUsingAlias(IngresoProductoPeer::FECHA, $fecha['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::FECHA, $fecha, $comparison);
    }

    /**
     * Filter the query on the tienda_id column
     *
     * Example usage:
     * <code>
     * $query->filterByTiendaId(1234); // WHERE tienda_id = 1234
     * $query->filterByTiendaId(array(12, 34)); // WHERE tienda_id IN (12, 34)
     * $query->filterByTiendaId(array('min' => 12)); // WHERE tienda_id > 12
     * </code>
     *
     * @see       filterByTienda()
     *
     * @param     mixed $tiendaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByTiendaId($tiendaId = null, $comparison = null)
    {
        if (is_array($tiendaId)) {
            $useMinMax = false;
            if (isset($tiendaId['min'])) {
                $this->addUsingAlias(IngresoProductoPeer::TIENDA_ID, $tiendaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($tiendaId['max'])) {
                $this->addUsingAlias(IngresoProductoPeer::TIENDA_ID, $tiendaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::TIENDA_ID, $tiendaId, $comparison);
    }

    /**
     * Filter the query on the empresa_id column
     *
     * Example usage:
     * <code>
     * $query->filterByEmpresaId(1234); // WHERE empresa_id = 1234
     * $query->filterByEmpresaId(array(12, 34)); // WHERE empresa_id IN (12, 34)
     * $query->filterByEmpresaId(array('min' => 12)); // WHERE empresa_id > 12
     * </code>
     *
     * @see       filterByEmpresa()
     *
     * @param     mixed $empresaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByEmpresaId($empresaId = null, $comparison = null)
    {
        if (is_array($empresaId)) {
            $useMinMax = false;
            if (isset($empresaId['min'])) {
                $this->addUsingAlias(IngresoProductoPeer::EMPRESA_ID, $empresaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($empresaId['max'])) {
                $this->addUsingAlias(IngresoProductoPeer::EMPRESA_ID, $empresaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::EMPRESA_ID, $empresaId, $comparison);
    }

    /**
     * Filter the query on the fecha_documento column
     *
     * Example usage:
     * <code>
     * $query->filterByFechaDocumento('fooValue');   // WHERE fecha_documento = 'fooValue'
     * $query->filterByFechaDocumento('%fooValue%'); // WHERE fecha_documento LIKE '%fooValue%'
     * </code>
     *
     * @param     string $fechaDocumento The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByFechaDocumento($fechaDocumento = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($fechaDocumento)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $fechaDocumento)) {
                $fechaDocumento = str_replace('*', '%', $fechaDocumento);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::FECHA_DOCUMENTO, $fechaDocumento, $comparison);
    }

    /**
     * Filter the query on the observaciones column
     *
     * Example usage:
     * <code>
     * $query->filterByObservaciones('fooValue');   // WHERE observaciones = 'fooValue'
     * $query->filterByObservaciones('%fooValue%'); // WHERE observaciones LIKE '%fooValue%'
     * </code>
     *
     * @param     string $observaciones The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByObservaciones($observaciones = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($observaciones)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $observaciones)) {
                $observaciones = str_replace('*', '%', $observaciones);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::OBSERVACIONES, $observaciones, $comparison);
    }

    /**
     * Filter the query on the numero_documento column
     *
     * Example usage:
     * <code>
     * $query->filterByNumeroDocumento('fooValue');   // WHERE numero_documento = 'fooValue'
     * $query->filterByNumeroDocumento('%fooValue%'); // WHERE numero_documento LIKE '%fooValue%'
     * </code>
     *
     * @param     string $numeroDocumento The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByNumeroDocumento($numeroDocumento = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($numeroDocumento)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $numeroDocumento)) {
                $numeroDocumento = str_replace('*', '%', $numeroDocumento);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::NUMERO_DOCUMENTO, $numeroDocumento, $comparison);
    }

    /**
     * Filter the query on the numero_orden column
     *
     * Example usage:
     * <code>
     * $query->filterByNumeroOrden('fooValue');   // WHERE numero_orden = 'fooValue'
     * $query->filterByNumeroOrden('%fooValue%'); // WHERE numero_orden LIKE '%fooValue%'
     * </code>
     *
     * @param     string $numeroOrden The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function filterByNumeroOrden($numeroOrden = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($numeroOrden)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $numeroOrden)) {
                $numeroOrden = str_replace('*', '%', $numeroOrden);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(IngresoProductoPeer::NUMERO_ORDEN, $numeroOrden, $comparison);
    }

    /**
     * Filter the query by a related Usuario object
     *
     * @param   Usuario|PropelObjectCollection $usuario The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   IngresoProductoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByUsuario($usuario, $comparison = null)
    {
        if ($usuario instanceof Usuario) {
            return $this
                ->addUsingAlias(IngresoProductoPeer::USUARIO_ID, $usuario->getId(), $comparison);
        } elseif ($usuario instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(IngresoProductoPeer::USUARIO_ID, $usuario->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByUsuario() only accepts arguments of type Usuario or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Usuario relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function joinUsuario($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Usuario');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Usuario');
        }

        return $this;
    }

    /**
     * Use the Usuario relation Usuario object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   UsuarioQuery A secondary query class using the current class as primary query
     */
    public function useUsuarioQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinUsuario($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Usuario', 'UsuarioQuery');
    }

    /**
     * Filter the query by a related Tienda object
     *
     * @param   Tienda|PropelObjectCollection $tienda The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   IngresoProductoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTienda($tienda, $comparison = null)
    {
        if ($tienda instanceof Tienda) {
            return $this
                ->addUsingAlias(IngresoProductoPeer::TIENDA_ID, $tienda->getId(), $comparison);
        } elseif ($tienda instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(IngresoProductoPeer::TIENDA_ID, $tienda->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByTienda() only accepts arguments of type Tienda or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tienda relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function joinTienda($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tienda');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tienda');
        }

        return $this;
    }

    /**
     * Use the Tienda relation Tienda object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TiendaQuery A secondary query class using the current class as primary query
     */
    public function useTiendaQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinTienda($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tienda', 'TiendaQuery');
    }

    /**
     * Filter the query by a related Empresa object
     *
     * @param   Empresa|PropelObjectCollection $empresa The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   IngresoProductoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByEmpresa($empresa, $comparison = null)
    {
        if ($empresa instanceof Empresa) {
            return $this
                ->addUsingAlias(IngresoProductoPeer::EMPRESA_ID, $empresa->getId(), $comparison);
        } elseif ($empresa instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(IngresoProductoPeer::EMPRESA_ID, $empresa->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByEmpresa() only accepts arguments of type Empresa or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Empresa relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function joinEmpresa($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Empresa');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Empresa');
        }

        return $this;
    }

    /**
     * Use the Empresa relation Empresa object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   EmpresaQuery A secondary query class using the current class as primary query
     */
    public function useEmpresaQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinEmpresa($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Empresa', 'EmpresaQuery');
    }

    /**
     * Filter the query by a related IngresoProductoDetalle object
     *
     * @param   IngresoProductoDetalle|PropelObjectCollection $ingresoProductoDetalle  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   IngresoProductoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByIngresoProductoDetalle($ingresoProductoDetalle, $comparison = null)
    {
        if ($ingresoProductoDetalle instanceof IngresoProductoDetalle) {
            return $this
                ->addUsingAlias(IngresoProductoPeer::ID, $ingresoProductoDetalle->getIngresoProductoId(), $comparison);
        } elseif ($ingresoProductoDetalle instanceof PropelObjectCollection) {
            return $this
                ->useIngresoProductoDetalleQuery()
                ->filterByPrimaryKeys($ingresoProductoDetalle->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByIngresoProductoDetalle() only accepts arguments of type IngresoProductoDetalle or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the IngresoProductoDetalle relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function joinIngresoProductoDetalle($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('IngresoProductoDetalle');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'IngresoProductoDetalle');
        }

        return $this;
    }

    /**
     * Use the IngresoProductoDetalle relation IngresoProductoDetalle object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   IngresoProductoDetalleQuery A secondary query class using the current class as primary query
     */
    public function useIngresoProductoDetalleQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinIngresoProductoDetalle($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'IngresoProductoDetalle', 'IngresoProductoDetalleQuery');
    }

    /**
     * Filter the query by a related InventarioVence object
     *
     * @param   InventarioVence|PropelObjectCollection $inventarioVence  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   IngresoProductoQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByInventarioVence($inventarioVence, $comparison = null)
    {
        if ($inventarioVence instanceof InventarioVence) {
            return $this
                ->addUsingAlias(IngresoProductoPeer::ID, $inventarioVence->getIngresoProductoId(), $comparison);
        } elseif ($inventarioVence instanceof PropelObjectCollection) {
            return $this
                ->useInventarioVenceQuery()
                ->filterByPrimaryKeys($inventarioVence->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByInventarioVence() only accepts arguments of type InventarioVence or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the InventarioVence relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function joinInventarioVence($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('InventarioVence');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'InventarioVence');
        }

        return $this;
    }

    /**
     * Use the InventarioVence relation InventarioVence object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   InventarioVenceQuery A secondary query class using the current class as primary query
     */
    public function useInventarioVenceQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinInventarioVence($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'InventarioVence', 'InventarioVenceQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   IngresoProducto $ingresoProducto Object to remove from the list of results
     *
     * @return IngresoProductoQuery The current query, for fluid interface
     */
    public function prune($ingresoProducto = null)
    {
        if ($ingresoProducto) {
            $this->addUsingAlias(IngresoProductoPeer::ID, $ingresoProducto->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
