<?php


/**
 * Base class that represents a query for the 'orden_cotizacion_empaque' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 08/13/26 04:50:35
 *
 * @method OrdenCotizacionEmpaqueQuery orderById($order = Criteria::ASC) Order by the id column
 * @method OrdenCotizacionEmpaqueQuery orderByOrdenCotizacionId($order = Criteria::ASC) Order by the orden_cotizacion_id column
 * @method OrdenCotizacionEmpaqueQuery orderByOrdenEmpaque($order = Criteria::ASC) Order by the orden_empaque column
 *
 * @method OrdenCotizacionEmpaqueQuery groupById() Group by the id column
 * @method OrdenCotizacionEmpaqueQuery groupByOrdenCotizacionId() Group by the orden_cotizacion_id column
 * @method OrdenCotizacionEmpaqueQuery groupByOrdenEmpaque() Group by the orden_empaque column
 *
 * @method OrdenCotizacionEmpaqueQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method OrdenCotizacionEmpaqueQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method OrdenCotizacionEmpaqueQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method OrdenCotizacionEmpaqueQuery leftJoinOrdenCotizacion($relationAlias = null) Adds a LEFT JOIN clause to the query using the OrdenCotizacion relation
 * @method OrdenCotizacionEmpaqueQuery rightJoinOrdenCotizacion($relationAlias = null) Adds a RIGHT JOIN clause to the query using the OrdenCotizacion relation
 * @method OrdenCotizacionEmpaqueQuery innerJoinOrdenCotizacion($relationAlias = null) Adds a INNER JOIN clause to the query using the OrdenCotizacion relation
 *
 * @method OrdenCotizacionEmpaque findOne(PropelPDO $con = null) Return the first OrdenCotizacionEmpaque matching the query
 * @method OrdenCotizacionEmpaque findOneOrCreate(PropelPDO $con = null) Return the first OrdenCotizacionEmpaque matching the query, or a new OrdenCotizacionEmpaque object populated from the query conditions when no match is found
 *
 * @method OrdenCotizacionEmpaque findOneById(int $id) Return the first OrdenCotizacionEmpaque filtered by the id column
 * @method OrdenCotizacionEmpaque findOneByOrdenCotizacionId(int $orden_cotizacion_id) Return the first OrdenCotizacionEmpaque filtered by the orden_cotizacion_id column
 * @method OrdenCotizacionEmpaque findOneByOrdenEmpaque(int $orden_empaque) Return the first OrdenCotizacionEmpaque filtered by the orden_empaque column
 *
 * @method array findById(int $id) Return OrdenCotizacionEmpaque objects filtered by the id column
 * @method array findByOrdenCotizacionId(int $orden_cotizacion_id) Return OrdenCotizacionEmpaque objects filtered by the orden_cotizacion_id column
 * @method array findByOrdenEmpaque(int $orden_empaque) Return OrdenCotizacionEmpaque objects filtered by the orden_empaque column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseOrdenCotizacionEmpaqueQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseOrdenCotizacionEmpaqueQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'OrdenCotizacionEmpaque', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new OrdenCotizacionEmpaqueQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     OrdenCotizacionEmpaqueQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return OrdenCotizacionEmpaqueQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof OrdenCotizacionEmpaqueQuery) {
            return $criteria;
        }
        $query = new OrdenCotizacionEmpaqueQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   OrdenCotizacionEmpaque|OrdenCotizacionEmpaque[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = OrdenCotizacionEmpaquePeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(OrdenCotizacionEmpaquePeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   OrdenCotizacionEmpaque A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `ORDEN_COTIZACION_ID`, `ORDEN_EMPAQUE` FROM `orden_cotizacion_empaque` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new OrdenCotizacionEmpaque();
            $obj->hydrate($row);
            OrdenCotizacionEmpaquePeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return OrdenCotizacionEmpaque|OrdenCotizacionEmpaque[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|OrdenCotizacionEmpaque[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the orden_cotizacion_id column
     *
     * Example usage:
     * <code>
     * $query->filterByOrdenCotizacionId(1234); // WHERE orden_cotizacion_id = 1234
     * $query->filterByOrdenCotizacionId(array(12, 34)); // WHERE orden_cotizacion_id IN (12, 34)
     * $query->filterByOrdenCotizacionId(array('min' => 12)); // WHERE orden_cotizacion_id > 12
     * </code>
     *
     * @see       filterByOrdenCotizacion()
     *
     * @param     mixed $ordenCotizacionId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     */
    public function filterByOrdenCotizacionId($ordenCotizacionId = null, $comparison = null)
    {
        if (is_array($ordenCotizacionId)) {
            $useMinMax = false;
            if (isset($ordenCotizacionId['min'])) {
                $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_COTIZACION_ID, $ordenCotizacionId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($ordenCotizacionId['max'])) {
                $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_COTIZACION_ID, $ordenCotizacionId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_COTIZACION_ID, $ordenCotizacionId, $comparison);
    }

    /**
     * Filter the query on the orden_empaque column
     *
     * Example usage:
     * <code>
     * $query->filterByOrdenEmpaque(1234); // WHERE orden_empaque = 1234
     * $query->filterByOrdenEmpaque(array(12, 34)); // WHERE orden_empaque IN (12, 34)
     * $query->filterByOrdenEmpaque(array('min' => 12)); // WHERE orden_empaque > 12
     * </code>
     *
     * @param     mixed $ordenEmpaque The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     */
    public function filterByOrdenEmpaque($ordenEmpaque = null, $comparison = null)
    {
        if (is_array($ordenEmpaque)) {
            $useMinMax = false;
            if (isset($ordenEmpaque['min'])) {
                $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_EMPAQUE, $ordenEmpaque['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($ordenEmpaque['max'])) {
                $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_EMPAQUE, $ordenEmpaque['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_EMPAQUE, $ordenEmpaque, $comparison);
    }

    /**
     * Filter the query by a related OrdenCotizacion object
     *
     * @param   OrdenCotizacion|PropelObjectCollection $ordenCotizacion The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByOrdenCotizacion($ordenCotizacion, $comparison = null)
    {
        if ($ordenCotizacion instanceof OrdenCotizacion) {
            return $this
                ->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_COTIZACION_ID, $ordenCotizacion->getId(), $comparison);
        } elseif ($ordenCotizacion instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(OrdenCotizacionEmpaquePeer::ORDEN_COTIZACION_ID, $ordenCotizacion->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByOrdenCotizacion() only accepts arguments of type OrdenCotizacion or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the OrdenCotizacion relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     */
    public function joinOrdenCotizacion($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('OrdenCotizacion');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'OrdenCotizacion');
        }

        return $this;
    }

    /**
     * Use the OrdenCotizacion relation OrdenCotizacion object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   OrdenCotizacionQuery A secondary query class using the current class as primary query
     */
    public function useOrdenCotizacionQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinOrdenCotizacion($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'OrdenCotizacion', 'OrdenCotizacionQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   OrdenCotizacionEmpaque $ordenCotizacionEmpaque Object to remove from the list of results
     *
     * @return OrdenCotizacionEmpaqueQuery The current query, for fluid interface
     */
    public function prune($ordenCotizacionEmpaque = null)
    {
        if ($ordenCotizacionEmpaque) {
            $this->addUsingAlias(OrdenCotizacionEmpaquePeer::ID, $ordenCotizacionEmpaque->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
