<?php


/**
 * Base class that represents a query for the 'orden_ubicacion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/30/25 15:40:28
 *
 * @method OrdenUbicacionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method OrdenUbicacionQuery orderByTiendaId($order = Criteria::ASC) Order by the tienda_id column
 * @method OrdenUbicacionQuery orderByProductoId($order = Criteria::ASC) Order by the producto_id column
 * @method OrdenUbicacionQuery orderByUbicacionId($order = Criteria::ASC) Order by the ubicacion_id column
 * @method OrdenUbicacionQuery orderByOrdenCotizacionId($order = Criteria::ASC) Order by the orden_cotizacion_id column
 * @method OrdenUbicacionQuery orderByProcesado($order = Criteria::ASC) Order by the procesado column
 * @method OrdenUbicacionQuery orderByCantidad($order = Criteria::ASC) Order by the cantidad column
 * @method OrdenUbicacionQuery orderByTiendaUbica($order = Criteria::ASC) Order by the tienda_ubica column
 * @method OrdenUbicacionQuery orderByVendedorProductoId($order = Criteria::ASC) Order by the vendedor_producto_id column
 * @method OrdenUbicacionQuery orderByOrdenVendedorId($order = Criteria::ASC) Order by the orden_vendedor_id column
 * @method OrdenUbicacionQuery orderBySalidaProductoId($order = Criteria::ASC) Order by the salida_producto_id column
 *
 * @method OrdenUbicacionQuery groupById() Group by the id column
 * @method OrdenUbicacionQuery groupByTiendaId() Group by the tienda_id column
 * @method OrdenUbicacionQuery groupByProductoId() Group by the producto_id column
 * @method OrdenUbicacionQuery groupByUbicacionId() Group by the ubicacion_id column
 * @method OrdenUbicacionQuery groupByOrdenCotizacionId() Group by the orden_cotizacion_id column
 * @method OrdenUbicacionQuery groupByProcesado() Group by the procesado column
 * @method OrdenUbicacionQuery groupByCantidad() Group by the cantidad column
 * @method OrdenUbicacionQuery groupByTiendaUbica() Group by the tienda_ubica column
 * @method OrdenUbicacionQuery groupByVendedorProductoId() Group by the vendedor_producto_id column
 * @method OrdenUbicacionQuery groupByOrdenVendedorId() Group by the orden_vendedor_id column
 * @method OrdenUbicacionQuery groupBySalidaProductoId() Group by the salida_producto_id column
 *
 * @method OrdenUbicacionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method OrdenUbicacionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method OrdenUbicacionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method OrdenUbicacionQuery leftJoinTienda($relationAlias = null) Adds a LEFT JOIN clause to the query using the Tienda relation
 * @method OrdenUbicacionQuery rightJoinTienda($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Tienda relation
 * @method OrdenUbicacionQuery innerJoinTienda($relationAlias = null) Adds a INNER JOIN clause to the query using the Tienda relation
 *
 * @method OrdenUbicacionQuery leftJoinProducto($relationAlias = null) Adds a LEFT JOIN clause to the query using the Producto relation
 * @method OrdenUbicacionQuery rightJoinProducto($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Producto relation
 * @method OrdenUbicacionQuery innerJoinProducto($relationAlias = null) Adds a INNER JOIN clause to the query using the Producto relation
 *
 * @method OrdenUbicacionQuery leftJoinOrdenCotizacion($relationAlias = null) Adds a LEFT JOIN clause to the query using the OrdenCotizacion relation
 * @method OrdenUbicacionQuery rightJoinOrdenCotizacion($relationAlias = null) Adds a RIGHT JOIN clause to the query using the OrdenCotizacion relation
 * @method OrdenUbicacionQuery innerJoinOrdenCotizacion($relationAlias = null) Adds a INNER JOIN clause to the query using the OrdenCotizacion relation
 *
 * @method OrdenUbicacionQuery leftJoinVendedorProducto($relationAlias = null) Adds a LEFT JOIN clause to the query using the VendedorProducto relation
 * @method OrdenUbicacionQuery rightJoinVendedorProducto($relationAlias = null) Adds a RIGHT JOIN clause to the query using the VendedorProducto relation
 * @method OrdenUbicacionQuery innerJoinVendedorProducto($relationAlias = null) Adds a INNER JOIN clause to the query using the VendedorProducto relation
 *
 * @method OrdenUbicacionQuery leftJoinOrdenVendedor($relationAlias = null) Adds a LEFT JOIN clause to the query using the OrdenVendedor relation
 * @method OrdenUbicacionQuery rightJoinOrdenVendedor($relationAlias = null) Adds a RIGHT JOIN clause to the query using the OrdenVendedor relation
 * @method OrdenUbicacionQuery innerJoinOrdenVendedor($relationAlias = null) Adds a INNER JOIN clause to the query using the OrdenVendedor relation
 *
 * @method OrdenUbicacionQuery leftJoinSalidaProducto($relationAlias = null) Adds a LEFT JOIN clause to the query using the SalidaProducto relation
 * @method OrdenUbicacionQuery rightJoinSalidaProducto($relationAlias = null) Adds a RIGHT JOIN clause to the query using the SalidaProducto relation
 * @method OrdenUbicacionQuery innerJoinSalidaProducto($relationAlias = null) Adds a INNER JOIN clause to the query using the SalidaProducto relation
 *
 * @method OrdenUbicacion findOne(PropelPDO $con = null) Return the first OrdenUbicacion matching the query
 * @method OrdenUbicacion findOneOrCreate(PropelPDO $con = null) Return the first OrdenUbicacion matching the query, or a new OrdenUbicacion object populated from the query conditions when no match is found
 *
 * @method OrdenUbicacion findOneById(int $id) Return the first OrdenUbicacion filtered by the id column
 * @method OrdenUbicacion findOneByTiendaId(int $tienda_id) Return the first OrdenUbicacion filtered by the tienda_id column
 * @method OrdenUbicacion findOneByProductoId(int $producto_id) Return the first OrdenUbicacion filtered by the producto_id column
 * @method OrdenUbicacion findOneByUbicacionId(string $ubicacion_id) Return the first OrdenUbicacion filtered by the ubicacion_id column
 * @method OrdenUbicacion findOneByOrdenCotizacionId(int $orden_cotizacion_id) Return the first OrdenUbicacion filtered by the orden_cotizacion_id column
 * @method OrdenUbicacion findOneByProcesado(boolean $procesado) Return the first OrdenUbicacion filtered by the procesado column
 * @method OrdenUbicacion findOneByCantidad(int $cantidad) Return the first OrdenUbicacion filtered by the cantidad column
 * @method OrdenUbicacion findOneByTiendaUbica(int $tienda_ubica) Return the first OrdenUbicacion filtered by the tienda_ubica column
 * @method OrdenUbicacion findOneByVendedorProductoId(int $vendedor_producto_id) Return the first OrdenUbicacion filtered by the vendedor_producto_id column
 * @method OrdenUbicacion findOneByOrdenVendedorId(int $orden_vendedor_id) Return the first OrdenUbicacion filtered by the orden_vendedor_id column
 * @method OrdenUbicacion findOneBySalidaProductoId(int $salida_producto_id) Return the first OrdenUbicacion filtered by the salida_producto_id column
 *
 * @method array findById(int $id) Return OrdenUbicacion objects filtered by the id column
 * @method array findByTiendaId(int $tienda_id) Return OrdenUbicacion objects filtered by the tienda_id column
 * @method array findByProductoId(int $producto_id) Return OrdenUbicacion objects filtered by the producto_id column
 * @method array findByUbicacionId(string $ubicacion_id) Return OrdenUbicacion objects filtered by the ubicacion_id column
 * @method array findByOrdenCotizacionId(int $orden_cotizacion_id) Return OrdenUbicacion objects filtered by the orden_cotizacion_id column
 * @method array findByProcesado(boolean $procesado) Return OrdenUbicacion objects filtered by the procesado column
 * @method array findByCantidad(int $cantidad) Return OrdenUbicacion objects filtered by the cantidad column
 * @method array findByTiendaUbica(int $tienda_ubica) Return OrdenUbicacion objects filtered by the tienda_ubica column
 * @method array findByVendedorProductoId(int $vendedor_producto_id) Return OrdenUbicacion objects filtered by the vendedor_producto_id column
 * @method array findByOrdenVendedorId(int $orden_vendedor_id) Return OrdenUbicacion objects filtered by the orden_vendedor_id column
 * @method array findBySalidaProductoId(int $salida_producto_id) Return OrdenUbicacion objects filtered by the salida_producto_id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseOrdenUbicacionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseOrdenUbicacionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'OrdenUbicacion', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new OrdenUbicacionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     OrdenUbicacionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return OrdenUbicacionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof OrdenUbicacionQuery) {
            return $criteria;
        }
        $query = new OrdenUbicacionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   OrdenUbicacion|OrdenUbicacion[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = OrdenUbicacionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(OrdenUbicacionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   OrdenUbicacion A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `TIENDA_ID`, `PRODUCTO_ID`, `UBICACION_ID`, `ORDEN_COTIZACION_ID`, `PROCESADO`, `CANTIDAD`, `TIENDA_UBICA`, `VENDEDOR_PRODUCTO_ID`, `ORDEN_VENDEDOR_ID`, `SALIDA_PRODUCTO_ID` FROM `orden_ubicacion` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new OrdenUbicacion();
            $obj->hydrate($row);
            OrdenUbicacionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return OrdenUbicacion|OrdenUbicacion[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|OrdenUbicacion[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(OrdenUbicacionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(OrdenUbicacionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the tienda_id column
     *
     * Example usage:
     * <code>
     * $query->filterByTiendaId(1234); // WHERE tienda_id = 1234
     * $query->filterByTiendaId(array(12, 34)); // WHERE tienda_id IN (12, 34)
     * $query->filterByTiendaId(array('min' => 12)); // WHERE tienda_id > 12
     * </code>
     *
     * @see       filterByTienda()
     *
     * @param     mixed $tiendaId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByTiendaId($tiendaId = null, $comparison = null)
    {
        if (is_array($tiendaId)) {
            $useMinMax = false;
            if (isset($tiendaId['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::TIENDA_ID, $tiendaId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($tiendaId['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::TIENDA_ID, $tiendaId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::TIENDA_ID, $tiendaId, $comparison);
    }

    /**
     * Filter the query on the producto_id column
     *
     * Example usage:
     * <code>
     * $query->filterByProductoId(1234); // WHERE producto_id = 1234
     * $query->filterByProductoId(array(12, 34)); // WHERE producto_id IN (12, 34)
     * $query->filterByProductoId(array('min' => 12)); // WHERE producto_id > 12
     * </code>
     *
     * @see       filterByProducto()
     *
     * @param     mixed $productoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByProductoId($productoId = null, $comparison = null)
    {
        if (is_array($productoId)) {
            $useMinMax = false;
            if (isset($productoId['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::PRODUCTO_ID, $productoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($productoId['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::PRODUCTO_ID, $productoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::PRODUCTO_ID, $productoId, $comparison);
    }

    /**
     * Filter the query on the ubicacion_id column
     *
     * Example usage:
     * <code>
     * $query->filterByUbicacionId('fooValue');   // WHERE ubicacion_id = 'fooValue'
     * $query->filterByUbicacionId('%fooValue%'); // WHERE ubicacion_id LIKE '%fooValue%'
     * </code>
     *
     * @param     string $ubicacionId The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByUbicacionId($ubicacionId = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($ubicacionId)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $ubicacionId)) {
                $ubicacionId = str_replace('*', '%', $ubicacionId);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::UBICACION_ID, $ubicacionId, $comparison);
    }

    /**
     * Filter the query on the orden_cotizacion_id column
     *
     * Example usage:
     * <code>
     * $query->filterByOrdenCotizacionId(1234); // WHERE orden_cotizacion_id = 1234
     * $query->filterByOrdenCotizacionId(array(12, 34)); // WHERE orden_cotizacion_id IN (12, 34)
     * $query->filterByOrdenCotizacionId(array('min' => 12)); // WHERE orden_cotizacion_id > 12
     * </code>
     *
     * @see       filterByOrdenCotizacion()
     *
     * @param     mixed $ordenCotizacionId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByOrdenCotizacionId($ordenCotizacionId = null, $comparison = null)
    {
        if (is_array($ordenCotizacionId)) {
            $useMinMax = false;
            if (isset($ordenCotizacionId['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::ORDEN_COTIZACION_ID, $ordenCotizacionId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($ordenCotizacionId['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::ORDEN_COTIZACION_ID, $ordenCotizacionId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::ORDEN_COTIZACION_ID, $ordenCotizacionId, $comparison);
    }

    /**
     * Filter the query on the procesado column
     *
     * Example usage:
     * <code>
     * $query->filterByProcesado(true); // WHERE procesado = true
     * $query->filterByProcesado('yes'); // WHERE procesado = true
     * </code>
     *
     * @param     boolean|string $procesado The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByProcesado($procesado = null, $comparison = null)
    {
        if (is_string($procesado)) {
            $procesado = in_array(strtolower($procesado), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::PROCESADO, $procesado, $comparison);
    }

    /**
     * Filter the query on the cantidad column
     *
     * Example usage:
     * <code>
     * $query->filterByCantidad(1234); // WHERE cantidad = 1234
     * $query->filterByCantidad(array(12, 34)); // WHERE cantidad IN (12, 34)
     * $query->filterByCantidad(array('min' => 12)); // WHERE cantidad > 12
     * </code>
     *
     * @param     mixed $cantidad The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByCantidad($cantidad = null, $comparison = null)
    {
        if (is_array($cantidad)) {
            $useMinMax = false;
            if (isset($cantidad['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::CANTIDAD, $cantidad['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($cantidad['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::CANTIDAD, $cantidad['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::CANTIDAD, $cantidad, $comparison);
    }

    /**
     * Filter the query on the tienda_ubica column
     *
     * Example usage:
     * <code>
     * $query->filterByTiendaUbica(1234); // WHERE tienda_ubica = 1234
     * $query->filterByTiendaUbica(array(12, 34)); // WHERE tienda_ubica IN (12, 34)
     * $query->filterByTiendaUbica(array('min' => 12)); // WHERE tienda_ubica > 12
     * </code>
     *
     * @param     mixed $tiendaUbica The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByTiendaUbica($tiendaUbica = null, $comparison = null)
    {
        if (is_array($tiendaUbica)) {
            $useMinMax = false;
            if (isset($tiendaUbica['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::TIENDA_UBICA, $tiendaUbica['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($tiendaUbica['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::TIENDA_UBICA, $tiendaUbica['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::TIENDA_UBICA, $tiendaUbica, $comparison);
    }

    /**
     * Filter the query on the vendedor_producto_id column
     *
     * Example usage:
     * <code>
     * $query->filterByVendedorProductoId(1234); // WHERE vendedor_producto_id = 1234
     * $query->filterByVendedorProductoId(array(12, 34)); // WHERE vendedor_producto_id IN (12, 34)
     * $query->filterByVendedorProductoId(array('min' => 12)); // WHERE vendedor_producto_id > 12
     * </code>
     *
     * @see       filterByVendedorProducto()
     *
     * @param     mixed $vendedorProductoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByVendedorProductoId($vendedorProductoId = null, $comparison = null)
    {
        if (is_array($vendedorProductoId)) {
            $useMinMax = false;
            if (isset($vendedorProductoId['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::VENDEDOR_PRODUCTO_ID, $vendedorProductoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($vendedorProductoId['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::VENDEDOR_PRODUCTO_ID, $vendedorProductoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::VENDEDOR_PRODUCTO_ID, $vendedorProductoId, $comparison);
    }

    /**
     * Filter the query on the orden_vendedor_id column
     *
     * Example usage:
     * <code>
     * $query->filterByOrdenVendedorId(1234); // WHERE orden_vendedor_id = 1234
     * $query->filterByOrdenVendedorId(array(12, 34)); // WHERE orden_vendedor_id IN (12, 34)
     * $query->filterByOrdenVendedorId(array('min' => 12)); // WHERE orden_vendedor_id > 12
     * </code>
     *
     * @see       filterByOrdenVendedor()
     *
     * @param     mixed $ordenVendedorId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterByOrdenVendedorId($ordenVendedorId = null, $comparison = null)
    {
        if (is_array($ordenVendedorId)) {
            $useMinMax = false;
            if (isset($ordenVendedorId['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::ORDEN_VENDEDOR_ID, $ordenVendedorId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($ordenVendedorId['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::ORDEN_VENDEDOR_ID, $ordenVendedorId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::ORDEN_VENDEDOR_ID, $ordenVendedorId, $comparison);
    }

    /**
     * Filter the query on the salida_producto_id column
     *
     * Example usage:
     * <code>
     * $query->filterBySalidaProductoId(1234); // WHERE salida_producto_id = 1234
     * $query->filterBySalidaProductoId(array(12, 34)); // WHERE salida_producto_id IN (12, 34)
     * $query->filterBySalidaProductoId(array('min' => 12)); // WHERE salida_producto_id > 12
     * </code>
     *
     * @see       filterBySalidaProducto()
     *
     * @param     mixed $salidaProductoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function filterBySalidaProductoId($salidaProductoId = null, $comparison = null)
    {
        if (is_array($salidaProductoId)) {
            $useMinMax = false;
            if (isset($salidaProductoId['min'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::SALIDA_PRODUCTO_ID, $salidaProductoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($salidaProductoId['max'])) {
                $this->addUsingAlias(OrdenUbicacionPeer::SALIDA_PRODUCTO_ID, $salidaProductoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(OrdenUbicacionPeer::SALIDA_PRODUCTO_ID, $salidaProductoId, $comparison);
    }

    /**
     * Filter the query by a related Tienda object
     *
     * @param   Tienda|PropelObjectCollection $tienda The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   OrdenUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByTienda($tienda, $comparison = null)
    {
        if ($tienda instanceof Tienda) {
            return $this
                ->addUsingAlias(OrdenUbicacionPeer::TIENDA_ID, $tienda->getId(), $comparison);
        } elseif ($tienda instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(OrdenUbicacionPeer::TIENDA_ID, $tienda->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByTienda() only accepts arguments of type Tienda or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Tienda relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function joinTienda($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Tienda');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Tienda');
        }

        return $this;
    }

    /**
     * Use the Tienda relation Tienda object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   TiendaQuery A secondary query class using the current class as primary query
     */
    public function useTiendaQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinTienda($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Tienda', 'TiendaQuery');
    }

    /**
     * Filter the query by a related Producto object
     *
     * @param   Producto|PropelObjectCollection $producto The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   OrdenUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByProducto($producto, $comparison = null)
    {
        if ($producto instanceof Producto) {
            return $this
                ->addUsingAlias(OrdenUbicacionPeer::PRODUCTO_ID, $producto->getId(), $comparison);
        } elseif ($producto instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(OrdenUbicacionPeer::PRODUCTO_ID, $producto->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByProducto() only accepts arguments of type Producto or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Producto relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function joinProducto($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Producto');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Producto');
        }

        return $this;
    }

    /**
     * Use the Producto relation Producto object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ProductoQuery A secondary query class using the current class as primary query
     */
    public function useProductoQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinProducto($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Producto', 'ProductoQuery');
    }

    /**
     * Filter the query by a related OrdenCotizacion object
     *
     * @param   OrdenCotizacion|PropelObjectCollection $ordenCotizacion The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   OrdenUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByOrdenCotizacion($ordenCotizacion, $comparison = null)
    {
        if ($ordenCotizacion instanceof OrdenCotizacion) {
            return $this
                ->addUsingAlias(OrdenUbicacionPeer::ORDEN_COTIZACION_ID, $ordenCotizacion->getId(), $comparison);
        } elseif ($ordenCotizacion instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(OrdenUbicacionPeer::ORDEN_COTIZACION_ID, $ordenCotizacion->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByOrdenCotizacion() only accepts arguments of type OrdenCotizacion or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the OrdenCotizacion relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function joinOrdenCotizacion($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('OrdenCotizacion');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'OrdenCotizacion');
        }

        return $this;
    }

    /**
     * Use the OrdenCotizacion relation OrdenCotizacion object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   OrdenCotizacionQuery A secondary query class using the current class as primary query
     */
    public function useOrdenCotizacionQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinOrdenCotizacion($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'OrdenCotizacion', 'OrdenCotizacionQuery');
    }

    /**
     * Filter the query by a related VendedorProducto object
     *
     * @param   VendedorProducto|PropelObjectCollection $vendedorProducto The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   OrdenUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByVendedorProducto($vendedorProducto, $comparison = null)
    {
        if ($vendedorProducto instanceof VendedorProducto) {
            return $this
                ->addUsingAlias(OrdenUbicacionPeer::VENDEDOR_PRODUCTO_ID, $vendedorProducto->getId(), $comparison);
        } elseif ($vendedorProducto instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(OrdenUbicacionPeer::VENDEDOR_PRODUCTO_ID, $vendedorProducto->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByVendedorProducto() only accepts arguments of type VendedorProducto or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the VendedorProducto relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function joinVendedorProducto($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('VendedorProducto');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'VendedorProducto');
        }

        return $this;
    }

    /**
     * Use the VendedorProducto relation VendedorProducto object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   VendedorProductoQuery A secondary query class using the current class as primary query
     */
    public function useVendedorProductoQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinVendedorProducto($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'VendedorProducto', 'VendedorProductoQuery');
    }

    /**
     * Filter the query by a related OrdenVendedor object
     *
     * @param   OrdenVendedor|PropelObjectCollection $ordenVendedor The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   OrdenUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByOrdenVendedor($ordenVendedor, $comparison = null)
    {
        if ($ordenVendedor instanceof OrdenVendedor) {
            return $this
                ->addUsingAlias(OrdenUbicacionPeer::ORDEN_VENDEDOR_ID, $ordenVendedor->getId(), $comparison);
        } elseif ($ordenVendedor instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(OrdenUbicacionPeer::ORDEN_VENDEDOR_ID, $ordenVendedor->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByOrdenVendedor() only accepts arguments of type OrdenVendedor or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the OrdenVendedor relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function joinOrdenVendedor($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('OrdenVendedor');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'OrdenVendedor');
        }

        return $this;
    }

    /**
     * Use the OrdenVendedor relation OrdenVendedor object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   OrdenVendedorQuery A secondary query class using the current class as primary query
     */
    public function useOrdenVendedorQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinOrdenVendedor($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'OrdenVendedor', 'OrdenVendedorQuery');
    }

    /**
     * Filter the query by a related SalidaProducto object
     *
     * @param   SalidaProducto|PropelObjectCollection $salidaProducto The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   OrdenUbicacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBySalidaProducto($salidaProducto, $comparison = null)
    {
        if ($salidaProducto instanceof SalidaProducto) {
            return $this
                ->addUsingAlias(OrdenUbicacionPeer::SALIDA_PRODUCTO_ID, $salidaProducto->getId(), $comparison);
        } elseif ($salidaProducto instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(OrdenUbicacionPeer::SALIDA_PRODUCTO_ID, $salidaProducto->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterBySalidaProducto() only accepts arguments of type SalidaProducto or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the SalidaProducto relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function joinSalidaProducto($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('SalidaProducto');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'SalidaProducto');
        }

        return $this;
    }

    /**
     * Use the SalidaProducto relation SalidaProducto object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   SalidaProductoQuery A secondary query class using the current class as primary query
     */
    public function useSalidaProductoQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinSalidaProducto($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'SalidaProducto', 'SalidaProductoQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   OrdenUbicacion $ordenUbicacion Object to remove from the list of results
     *
     * @return OrdenUbicacionQuery The current query, for fluid interface
     */
    public function prune($ordenUbicacion = null)
    {
        if ($ordenUbicacion) {
            $this->addUsingAlias(OrdenUbicacionPeer::ID, $ordenUbicacion->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
