<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2025/12/28 02:40:50
sfConfig::add(array(
  'mod_marca_producto_enabled' => true,
  'mod_marca_producto_view_class' => 'sfPHP',
));
