<?php



/**
 * Skeleton subclass for representing a row from the 'cheque' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 03/15/22 16:05:41
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Cheque extends BaseCheque
{
    
     public function getTipoDetalle() {
      $retorna ='Pago Proveedor';
      if ($this->getOrdenDevolucionId()) { 
          $retorna = "Devolucion ".$this->getOrdenDevolucion()->getCodigo();
      } 
      if ($this->getSolicitudCheque ()) { 
          $retorna = "Solciitud ".$this->getSolicitudCheque()->getCodigo();
      } 

      return $retorna;
         
     }
}
