<?php

/**
 * Skeleton subclass for representing a row from the 'cliente' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 01/11/22 01:11:40
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Cliente extends BaseCliente {

    
    public function getTipoCliente () {
     //   $campo
        $datoQ = ValorUsuarioQuery::create()
                
                 ->filterByTipoDocumento('Cliente')
                 ->filterByNoDocumento($this->getId())
                ->useCampoUsuarioQuery()
                ->filterByNombre('TIPO_CLIENTE')
                ->endUse()
                ->findOne();
        $valor ='';
        if ($datoQ) {
            $valor=$datoQ->getValor();
        }
        
       return $valor;
    }
    
    public function getCodigoCli() {
        $rerun = $this->getCodigo();
        $rerun = str_replace("CONTRAENTREGA", "", $rerun);
        RETURN $rerun;
    }

    public function getFacturaPendiente() {
        $NIT = $this->getNit();
        $NIT = str_replace(".", "", $NIT);
        $NIT = str_replace("/", "", $NIT);
        $NIT = str_replace("-", "", $NIT);
        $NIT = str_replace("_", "", $NIT);
        $NIT = str_replace(" ", "", $NIT);
        $NIT = strtoupper(TRIM($NIT));
        $CODIGO = '';
        if ($NIT <> "") {
            if ($NIT <> 'CF') {
                $operacion = OperacionQuery::create()
                        ->filterByPermiteFacturar(true, Criteria::NOT_EQUAL)
                        ->filterByNit($this->getNit())
                        ->filterByPagado(false)
                        ->where("Operacion.Fecha < DATE_SUB(NOW(), INTERVAL 6 MONTH)")
                        ->findOne();
                if ($operacion) {
                    $CODIGO = $operacion->getCodigo();
                }
            }
        }
        $operacion = OperacionQuery::create()
                                        ->filterByPermiteFacturar(true, Criteria::NOT_EQUAL)
                ->useClienteQuery()
                ->filterByCodigo($this->getCodigo())
                ->endUse()
                 ->filterByPagado(false)
               ->where("Operacion.Fecha < DATE_SUB(NOW(), INTERVAL 6 MONTH)")
                ->findOne();
        if ($operacion) {
            $CODIGO = $operacion->getCodigo();
        }
//        $CODIGO='asdasd';
        return $CODIGO;
    }

    static public function pobladatos($id) {
        $usuarioId = sfContext::getInstance()->getUser()->getAttribute('usuario', null, 'seguridad');
        $lineaInicial = 1;
        header('Content-type: text/plain; charset=utf-8');
        $bitacora = BitacoraArchivoQuery::create()->findOneById($id);
        sfContext::getInstance()->getUser()->setAttribute('muestrabusqueda', 0, 'busqueda');
        $filename = $bitacora->getNombre();
        $inputFileName = sfConfig::get("sf_upload_dir") . DIRECTORY_SEPARATOR . 'cargas' . DIRECTORY_SEPARATOR . $filename;
        $objReader = new PHPExcel_Reader_Excel5();
        $objPHPExcel = $objReader->load($inputFileName);
        $sheetData = $objPHPExcel->getActiveSheet()->toArray(null, true, true, true);
        $contador = 0;
        $colCODIGO = null;
        $colACCOUNT = null;
        $colDESCRIPTION = null;
        $colAQUISITION = null;
        $colLIFE_YEAR = null;
        $colBOOK_VALUE = null;
        $col_POR = null;
        $colENDING = null;
        $datos = null;
        $NUMERO = 0;
        $pendientes = null;
//        echo "<pre>";
//        print_r($sheetData);
//        die();
        foreach ($sheetData as $registro) {
            $contador++;
            $lista = null;
            $CODIGO = null;
            $ACCOUNT = null;
            $DESCRIPTION = null;
            $AQUISITION = null;
            $LIFE_YEAR = null;
            $BOOK_VALUE = null;
            $POR = null;
            //  $ENDING = null;
            $lin = $lineaInicial;
            $valido = true;

            if ($contador == $lineaInicial) {
                for ($i = 0; $i <= 7; $i++) {
                    $letra = CorrelativoCodigoQuery::numeroletra($i); //sfContext::getInstance()->getUser()->numeroletra($i);
                    $campo = trim(strtoupper(($registro[$letra])));
                    $campo = ($campo);
//                    $campo = ProveedorPeer::limpiatil($campo);
                    $campo = trim(strtoupper($campo));
                    $campo = str_replace(" ", "", $campo); //                  
//                         echo $campo;
//                        echo " ------------- ";
                    switch ($campo) {
                        case 'CODIGO':
                            $colCODIGO_COPHER = $letra;
                            break;
                        case 'ACCOUNT':
                            $colACCOUNT = $letra;
                            break;
                        case 'DESCRIPTION':
                            $colDESCRIPTION = $letra;
                            break;
                        case 'ADQUISITION':
                            $colAQUISITION = $letra;
                            break;
//                        case 'ENDING':
//                            $colENDING = $letra;
//                            break;
                        case 'LIFE':
                            $colLIFE_YEAR = $letra;
                            break;
                        case 'BOOK':
                            $colBOOK_VALUE = $letra;
                            break;
                        case '%':
                            $col_POR = $letra;
                            break;
                    }
                }
                //     die();
            }

            $mensaje = '';
            if ($contador > $lineaInicial) {
                $NUMERO++;
                if (array_key_exists($colCODIGO, $registro)) {
                    $CODIGO_COPHER = trim(($registro[$colCODIGO]));
                } else {
                    $valido = false;
                    $pendientes[] = 'Codigo';
                }
                if (array_key_exists($colACCOUNT, $registro)) {
                    $ACCOUNT = trim(($registro[$colACCOUNT]));
                } else {
                    $valido = false;
                    $pendientes[] = 'Account';
                }
                if (array_key_exists($colDESCRIPTION, $registro)) {
                    $DESCRIPTION = trim(($registro[$colDESCRIPTION]));
                } else {
                    $valido = false;
                    $pendientes[] = 'Description';
                }
                if (array_key_exists($colAQUISITION, $registro)) {
                    $AQUISITION = trim(($registro[$colAQUISITION]));
                } else {
                    $valido = false;
                    $pendientes[] = 'Adquisition';
                }
                if (array_key_exists($colLIFE_YEAR, $registro)) {
                    $LIFE_YEAR = trim(($registro[$colLIFE_YEAR]));
                } else {
                    $valido = false;
                    $pendientes[] = 'Life';
                }
                if (array_key_exists($colBOOK_VALUE, $registro)) {
                    $BOOK_VALUE = trim(($registro[$colBOOK_VALUE]));
                } else {
                    $valido = false;
                    $pendientes[] = 'Book';
                }
                if (array_key_exists($col_POR, $registro)) {
                    $POR = trim(($registro[$col_POR]));
                } else {
                    $valido = false;
                    $pendientes[] = '%';
                }
//                if (array_key_exists($colENDING, $registro)) {
//                    $NOMBRECUENTA = trim(($registro[$colENDING]));
//                } else {
//                    $valido = false;
//                    $pendientes[] = 'Ending';
//                }


                $ACCOUNT = str_replace("-", "", $ACCOUNT);
                $ACCOUNT = trim($ACCOUNT);
                if (strlen($ACCOUNT) > 5) {
                    $SeparaGuion = explode("-", $AQUISITION);
                    $cantida = count($SeparaGuion);
                    if ($cantida > 2) {
                        $ano = $SeparaGuion[2];
                        if (strlen($SeparaGuion[2]) == 2) {
                            if ($ano > 50) {
                                $ano = "19" . $ano;
                            } else {
                                $ano = "20" . $ano;
                            }
                        }
                        $AQUISITION = $ano . "-" . $SeparaGuion[0] . "-" . $SeparaGuion[1];
                    }

                    $SeparaSlash = explode("/", $AQUISITION);
                    $cantida = count($SeparaSlash);
                    if ($cantida > 2) {
                        $ano = $SeparaSlash[2];
                        if (strlen($SeparaSlash[2]) == 2) {


                            if ($ano > 50) {
                                $ano = "19" . $ano;
                            } else {
                                $ano = "20" . $ano;
                            }
                        }
                        $AQUISITION = $ano . "-" . $SeparaSlash[1] . "-" . $SeparaSlash[0];
                    }

                    $BOOK_VALUE = strtoupper($BOOK_VALUE);
                    $BOOK_VALUE = str_replace("Q", "", $BOOK_VALUE);
                    $BOOK_VALUE = str_replace("%", "", $BOOK_VALUE);
                    $BOOK_VALUE = str_replace(",", "", $BOOK_VALUE);
                    $BOOK_VALUE = str_replace(" ", "", $BOOK_VALUE);
                    $BOOK_VALUE = ltrim(rtrim($BOOK_VALUE));
                    $POR = strtoupper($POR);
                    $POR = str_replace("Q", "", $POR);
                    $POR = str_replace("%", "", $POR);
                    $POR = str_replace(",", "", $POR);
                    $POR = str_replace(" ", "", $POR);
                    $POR = ltrim(rtrim($POR));

                    $LIFE_YEAR = strtoupper($LIFE_YEAR);
                    $LIFE_YEAR = str_replace("Q", "", $LIFE_YEAR);
                    $LIFE_YEAR = str_replace("%", "", $LIFE_YEAR);
                    $LIFE_YEAR = str_replace(",", "", $LIFE_YEAR);
                    $LIFE_YEAR = str_replace(" ", "", $LIFE_YEAR);
                    $LIFE_YEAR = ltrim(rtrim($LIFE_YEAR));

                    $cuentaId = null;
                    $NOMBRECUENTA = '';
                    $cuentaContable = CuentaErpContableQuery::create()
                            ->where(" REPLACE(CuentaErpContable.CuentaContable,'-','') = '" . $ACCOUNT . "'")
                            ->findOne();
                    if ($cuentaContable) {
                        $cuentaId = $cuentaContable->getId();
                        $NOMBRECUENTA = $cuentaContable->getNombre();
                    }

                    $AQUISITIONvENCE = date("Y-m-d", strtotime($AQUISITION . "+ " . $LIFE_YEAR . " year"));

                    if (trim($CODIGO) == "") {
                        $listaC[$ACCOUNT][] = $ACCOUNT;

                        $listaCo = ListaActivosQuery::create()
                                ->withColumn('max(CAST(SUBSTR(ListaActivos.Codigo,8,12) AS DECIMAL)) ', 'NumeroMax')
                                ->filterByCuentaContable($ACCOUNT)
                                ->findOne();
                        $suma = count($listaC[$ACCOUNT]);
                        if ($listaCo) {
                            $NumeroActual = $listaCo->getNumeroMax() + $suma;
                            $CODIGO = $ACCOUNT . "-" . $NumeroActual;
                        }
                    }

//                   ECHO $AQUISITION;
//                   echo '<br>';
//                   echo $LIFE_YEAR;
//                   echo "<br>";
//                   echo $AQUISITIONvENCE;
//                   die();
                    //if ($valido == true) {
                    $existe = ListaActivosQuery::create()
                            ->filterByCodigo($CODIGO)
                            ->count();
                    $id = null;
                    if ($existe) {
                        $existqQ = ListaActivosQuery::create()->findOneByCodigo($CODIGO);
                        $id = $existqQ->getId();
                    }
                    $lista['LINEA'] = $contador;
                    $lista['CODIGO'] = $CODIGO;
                    $lista['ACCOUNT'] = $ACCOUNT;
                    $lista['DESCRIPTION'] = $DESCRIPTION;
                    $lista['ADQUISITION'] = $AQUISITION;
                    $lista['ADQUISITIONvENCE'] = $AQUISITIONvENCE;
                    $lista['VENCIDO'] = FALSE;
                    $lista['ACUALIZADO'] = $existe;

//                    if ($AQUISITIONvENCE < date('Y-m-d')) {
//                        $lista['VENCIDO'] = TRUE;
//                    }
                    $lista['LIFE'] = $LIFE_YEAR;
                    $lista['BOOK'] = $BOOK_VALUE;
                    $lista['POR'] = $POR;
                    $lista['CUENTA_ID'] = $cuentaId;
                    $lista['NOMBRE_CUENTA'] = $NOMBRECUENTA;
                    $lista['ID'] = $id;
                    if ($BOOK_VALUE) {
                        if ($POR) {
                            if ($LIFE_YEAR) {
                                $datos[$NUMERO] = $lista;
                            }
                        }
                    }
                }
                // }
            }
        }
        $resultado['datos'] = $datos;
        $resultado['valido'] = $valido;
        $resultado['pendiente'] = $pendientes;
        if ($valido) {
            sfContext::getInstance()->getUser()->setAttribute('seledatos', serialize($datos), 'carga');
        }
//        echo "<pre>";
//        print_r($resultado);
//        echo "</pre>";
//        die();
        return $resultado;
    }

    public function save(PropelPDO $con = null) {
        $empresaId = UsuarioQuery::getEmpresaSeleccionada('Cliente');

        if ($empresaId) {
            $this->setEmpresaId($empresaId);
        }
        if (trim($this->getCodigo()) == "") {
            $tipo = $empresaId . 'CI';
            $pre = $empresaId . 'CLI';
            $numero = 1;
            $busca = CorrelativoCodigoQuery::create()
                    ->filterByTipo($tipo)
                    ->findOne();
            if (!$busca) {
                $busca = New CorrelativoCodigo();
                $busca->setTipo($tipo);
                $busca->setPrefijo($pre);
                $busca->setNumeroAsginar($numero);
                $busca->save();
            }
            $numero = $busca->getNumeroAsginar();
            $numero = $busca->getNumeroAsginar();
            $prefijo = $pre . $numero;
            if (strlen($numero) == 1) {
                $prefijo = $pre . '0' . $numero;
            }
            if ($numero > 99) {
                $prefijo = $pre . $numero;
            }
            $this->setCodigo($prefijo);

            $busca->setNumeroAsginar($numero + 1);
            $busca->save();
        }


        parent::save($con);
    }

    public function getDireccionCompleta() {
        $departamento = '';
        $municipio = '';
        $municipioQuery = MunicipioQuery::create()->findOneById($this->getMunicipioId());
        $deptoQuery = DepartamentoQuery::create()->findOneById($this->getDepartamentoId());
        if ($municipioQuery) {
            $municipio = $municipioQuery->getDescripcion();
        }
        if ($deptoQuery) {
            $departamento = $deptoQuery->getNombre();
        }

        $retorna = $this->getDireccion() . " " . $departamento . " " . $municipio;
        return $retorna;
    }

}
