<?php

/**
 * Skeleton subclass for performing query and update operations on the 'orden_cotizacion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 01/31/22 22:53:48
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class OrdenCotizacionPeer extends BaseOrdenCotizacionPeer {

    static public function ProcesaAutoUbicacion($cotizacion) {
        error_reporting(-1);
        date_default_timezone_set("America/Guatemala");
        // **** CREACION DE OPERACION 
        $operacion = OperacionQuery::create()->findOneByCodigo($cotizacion->getCodigo());
        if (!$operacion) {
            $operacion = new Operacion();
            $operacion->setCodigo($cotizacion->getCodigo());
            $operacion->save();
        }
        $tiendaQ = TiendaQuery::create()->findOneById($cotizacion->getTiendaId());
        if (!$tiendaQ) {
            $tiendaQ = TiendaQuery::create()->findOne();
        }
        $operacion->setCodigoEstablecimiento($tiendaQ->getCodigoEstablecimiento());
        $operacion->setFecha($cotizacion->getFecha('Y-m-d'));
        $operacion->setTipo("Cotizacion");
        $operacion->setEstatus('Procesada');
        $operacion->setObservaciones($cotizacion->getComentario());
        $operacion->setNombre($cotizacion->getNombre());
        $operacion->setUsuario(sfContext::getInstance()->getUser()->getAttribute('usuarioNombre', null, 'seguridad'));
        $operacion->setNit($cotizacion->getNit());
        $operacion->setCorreo($cotizacion->getCorreo());
        $operacion->setValorTotal($cotizacion->getValorTotal());
        $operacion->setIva($cotizacion->getIva());
        $operacion->setSubTotal($cotizacion->getSubTotal());
        $operacion->setTiendaId($cotizacion->getTiendaId());
        $operacion->setVendedorId($cotizacion->getVendedorId());
        $operacion->setObservaciones($cotizacion->getComentario());
        $operacion->setRecetarioId($cotizacion->getRecetarioId());
        $operacion->setPesoTotal($cotizacion->getPesoTotal());
        $operacion->setPaisId($cotizacion->getPaisId());
        $operacion->setCantidadTotalCaja($cotizacion->getCantidadTotalCaja());
        if ($cotizacion->getClienteId()) {
            $operacion->setClienteId($cotizacion->getClienteId());
        }
        $operacion->save();
        /// ** FIN CREACION
        $ordenDetalle = OrdenCotizacionDetalleQuery::create()
                ->filterByCantidad(0, Criteria::GREATER_THAN)
                ->filterByOrdenCotizacionId($cotizacion->getId())
                ->find();
        $bodegaId = $operacion->getTiendaId();
        $empresaId = $operacion->getEmpresaId();
        $totalVal = 0;
        $totalIva = 0;
        foreach ($ordenDetalle as $regi) {
            //** CREACION DE LINEA
            $valorlineaTOTAL = $regi->getValorUnitario() * $regi->getCantidad();
            $valorlineaTOTAL = round($valorlineaTOTAL, 2);
            $IVA = round($valorlineaTOTAL - ($valorlineaTOTAL / 1.12), 2);

            $detalle = new OperacionDetalle();
            $detalle->setServicioId($regi->getServicioId());
            $detalle->setCodigo($regi->getCodigo());
            $detalle->setOperacionId($operacion->getId());
            $detalle->setProductoId($regi->getProductoId());
            $detalle->setDetalle($regi->getDetalle());
            $detalle->setValorUnitario($regi->getValorUnitario());
            $detalle->setValorTotal($valorlineaTOTAL);
            $detalle->setTotalIva($IVA);
            $detalle->setCantidad($regi->getCantidad());
            $detalle->setCostoUnitario($regi->getCostoUnitario());
            $detalle->setLineaNo($regi->getId());


            $con = Propel::getConnection();
            $con->beginTransaction();
            try {
                $regi = $detalle;
                $totalVal = $totalVal + $valorlineaTOTAL;
                $totalIva = $totalIva + $IVA;
                $detalle->save();
                $con->commit();
            } catch (Exception $ex) {
                $mensaje = $ex->getMessage();
                $texto = date('Y-m-d H:i:s') . "  linea   " . $regi->getId() . "        " . $mensaje . " ----------  \n <br> ";
                $ruta = sfConfig::get("sf_upload_dir") . DIRECTORY_SEPARATOR . "erores.txt";
                $fh = fopen($ruta, 'a');
                fwrite($fh, $texto);
                fclose($fh);
                $con->rollback();
            }

            $ordenUbicacion = OrdenUbicacionQuery::create()
                    ->filterByOrdenCotizacionId($cotizacion->getId())
                    ->filterByProductoId($regi->getProductoId())
                    ->count();
            if ($ordenUbicacion == 0) {
                $productoQuery = ProductoQuery::create()->findOneById($regi->getProductoId());
                if ($productoQuery) {
                    $clave = $productoQuery->getId();
                    $valoresIVa = ParametroQuery::ObtenerIva($regi->getValorTotal(), false);
                    ProductoMovimientoQuery::Salida($clave, $regi->getCantidad(), 'VENTA', $operacion->getTiendaId(), $operacion->getCodigo() . "-" . $regi->getId(), null, $valoresIVa);
                    ProductoExistenciaQuery::Resta($clave, $regi->getCantidad(), $bodegaId);
                    $ListaProductos = ProductoExistenciaQuery::create()
                            ->filterByEmpresaId($empresaId)
                            ->filterByProductoId($clave)
                            ->withColumn('sum(ProductoExistencia.Cantidad)', 'ValorTotal')
                            ->findOne();
                    $nuevaExistencia = $ListaProductos->getValorTotal();
                    $productoQuery->setExistencia($nuevaExistencia);
                    $productoQuery->save();
                }
            }
            // ** FIN LINEA
        }
        $operacion->setValorTotal($totalVal);
        $operacion->setIva($totalIva);
        $operacion->setSubTotal($totalVal - $totalIva);
        $operacion->save();

        BitacoraDocumento::grabacion('Cotizacion', $cotizacion->getCodigo(), 'Finalizacion', "Cotizacion Finalizada");

        $PROCESADO = false;
        $ubicacionesPro = OrdenUbicacionQuery::create()
                ->filterByProductoId(null, Criteria::NOT_EQUAL)
                ->filterByProcesado(false)
                ->filterByOrdenCotizacionId($cotizacion->getId())
                ->find();
        foreach ($ubicacionesPro as $lista) {
            $productoQuery = ProductoQuery::create()->findOneById($lista->getProductoId());
            $clave = $lista->getProductoId();
            $llave = $cotizacion->getId() . "_" . $lista->getProductoId() . "_" . $lista->getUbicacionId();
//         echo $llave;
//         die();
            $movimientoId = ProductoMovimientoQuery::Salida($clave, $lista->getCantidad(), 'VENTA', $lista->getTiendaUbica(), $operacion->getCodigo() . "-" . $lista->getUbicacionId(), null, null, $llave);
            if ($movimientoId > 0) {
                ProductoExistenciaQuery::Resta($clave, $lista->getCantidad(), $lista->getTiendaUbica());
                $ListaProductos = ProductoExistenciaQuery::create()
                        ->filterByEmpresaId($empresaId)
                        ->filterByProductoId($clave)
                        ->withColumn('sum(ProductoExistencia.Cantidad)', 'ValorTotal')
                        ->findOne();
                $nuevaExistencia = $ListaProductos->getValorTotal();
                $productoQuery->setExistencia($nuevaExistencia);
                $productoQuery->save();
                $ubicacActual = ProductoUbicacionQuery::create()
                        ->filterByUbicacion($lista->getUbicacionId())
                        ->filterByProductoId($lista->getProductoId())
                        ->filterByTiendaId($lista->getTiendaUbica())
                        ->findOne();
                if ($ubicacActual) {
                    $PROCESADO = true;
                    $existeActual = $ubicacActual->getCantidad();
                    $nuevaCantidad = $existeActual - $lista->getCantidad();
                    $ubicacActual->setCantidad($nuevaCantidad);
                    $ubicacActual->save();
                }
                $lista->setProcesado(true);
                $lista->save();
            }
        }


        return $operacion->getId();
    }

}
