<?php

/**
 * Skeleton subclass for representing a row from the 'tasa_cambio' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 11/24/22 23:59:22
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TasaCambio extends BaseTasaCambio {

    static public function Tasas() {
           date_default_timezone_set("America/Guatemala");
     
        $parametros['fechainit'] = '01/10/2022';
        $parametros['fechainit'] = date('d/m/Y');
        $tasaCambioDia = TasaCambioQuery::create()->findOne(); //ByFecha(date('Y-m-d'));

        if (!$tasaCambioDia) {
               $WSDL = 'https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx?wsdl';
        $client = new SoapClient($WSDL);
            $resultado = $client->TipoCambioFechaInicial($parametros);
            $listado = $resultado->TipoCambioFechaInicialResult->Vars->Var;
            $registros= count($listado);
            if ($registros==1) {
                $fecha = $listado->fecha;
                $venta = $listado->venta;
                $fechaFin = explode('/', $fecha);
                $fechaFin = $fechaFin[2] . '-' . $fechaFin[1] . '-' . $fechaFin[0];
                $tasaCambio = TasaCambioQuery::create()->findOneByFecha($fechaFin);
              //   echo $fechaFin . " " . $venta;
                if (!$tasaCambio) {
                    $tasaCambio = New TasaCambio();
                    $tasaCambio->setFecha($fechaFin);
                }
                $tasaCambio->setValor($venta);
                $tasaCambio->save();
            }
            
            if ($registros >1) {
                foreach ($listado as $lista) {
                $fecha = $lista->fecha;
                $venta = $lista->venta;
                $fechaFin = explode('/', $fecha);
                $fechaFin = $fechaFin[2] . '-' . $fechaFin[1] . '-' . $fechaFin[0];
//                echo $fechaFin . " " . $venta;
//                echo "<br>";
                $tasaCambio = TasaCambioQuery::create()->findOneByFecha($fechaFin);
                if (!$tasaCambio) {
                    $tasaCambio = New TasaCambio();
                    $tasaCambio->setFecha($fechaFin);
                }
                $tasaCambio->setValor($venta);
                $tasaCambio->save();
            }
            }
        }
      

    }

       static public function TasaDia($dia=null) {
              date_default_timezone_set("America/Guatemala");
              $tasaQue = TasaCambioQuery::create()->findOneByFecha(date('Y-m-d'));
              if ($dia) {
              $tasaQue = TasaCambioQuery::create()->findOneByFecha($dia);
                  
              }
              $tasa=0.00;
              if ($tasaQue) {
                  $tasa= $tasaQue->getValor();
              }
              return $tasa;              
       }
        static public function TasaPromedio() {
           date_default_timezone_set("America/Guatemala");
          $fechaInicio = date('Y-m-01');              
          $fechaFin = date('Y-m-d');
          $tasa=0.00;
          $tasaCambio = TasaCambioQuery::create()
              ->where("TasaCambio.Fecha >= '" . $fechaInicio . " 00:00:00" . "'")
              ->where("TasaCambio.Fecha <= '" . $fechaFin . " 23:59:00" . "'")
              ->withColumn('avg(TasaCambio.Valor)', 'ValorTotal')
                  ->findOne();
         
          if ($tasaCambio) {
              $tasa=$tasaCambio->getValorTotal();
          }
       return $tasa;
       }
}
