<?php

/**
 * Skeleton subclass for performing query and update operations on the 'tipo_aparato' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 12/09/19 04:42:06
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TipoAparatoQuery extends BaseTipoAparatoQuery {

    public function __construct($dbName = 'propel', $modelName = 'TipoAparato', $modelAlias = null) {
        parent::__construct($dbName, $modelName, $modelAlias);
        $empresa_id = UsuarioQuery::getEmpresaSeleccionada('TipoAparato');
        $filtra = sfContext::getInstance()->getUser()->getAttribute('usuario', null, 'filtra_empresa');
        if ($filtra) {
            if ($empresa_id) {
                $this->filterByEmpresaId($empresa_id);
            }
        }
    }

    static public function tipo() {
        return "Grupo";
    }

    static public function marca() {
        return "SubGrupo";
    }

    static public function modelo() {
        return "Categoria";
    }

}
