<?php



/**
 * Skeleton subclass for performing query and update operations on the 'traslado_producto' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 09/04/25 05:33:25
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TrasladoProductoQuery extends BaseTrasladoProductoQuery
{
    
        public function __construct($dbName = 'propel', $modelName = 'TrasladoProducto', $modelAlias = null) {
        parent::__construct($dbName, $modelName, $modelAlias);
        $empresa_id = UsuarioQuery::getEmpresaSeleccionada('TrasladoProducto');
        $filtra = sfContext::getInstance()->getUser()->getAttribute('usuario', null, 'filtra_empresa');
        $filtra = true;
        if ($filtra) {
            if ($empresa_id) {
                $this->filterByEmpresaId($empresa_id);
            }
        }
    }
}
