<?php



/**
 * Skeleton subclass for performing query and update operations on the 'usuario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * 05/02/15 04:55:15
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class UsuarioPeer extends BaseUsuarioPeer
{
       static public function correoBienvenido($nombreCompleto, $usuario, $clave,$correo) {

        $titulo="Registro de Usuario VeniaLink";
        $texto = '<p><img src="https://admin.posvirtual.com.gt/images/linkvisa.png" alt="" width="406" height="109" /></p>
<h3><strong>' . $nombreCompleto . '</strong></h3>
<h2><span style="color: #008080;"><strong>Te damos la Bienvenida</strong></span></h2>
<p>Para poder acceder utiliza los siguientes datos</p>
<ul style="list-style-type: circle;">
<li><strong>Usuario: </strong> &nbsp;' . $usuario . '&nbsp;</li>
<li><strong>Clave: </strong>' . $clave . '</strong></li>
<li><strong>Acceder:&nbsp; &nbsp;</strong></li>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://adminpos.shopshop.com.gt/index.php"><strong><img src="http://adminpos.shopshop.com.gt/images/logo_pdv.png" alt="" width="205" height="70" /></strong></a>
</ul>';
   
        UsuarioPeer::sendEmail($texto, $titulo, $correo);
        
    }
    
    
        static public function correoRecupera($nombreCompleto,$usuario, $token,$correo) {

        $titulo="Recuperación de Accesos   PDV";
        $texto = '<p><img src="https://admin.posvirtual.com.gt/images/linkvisa.png" alt="" width="406" height="109" /></p>
<h3><strong>' . $nombreCompleto . '</strong></h3>
<h2><span style="color: #008080;"><strong>Recuperaci&oacute;n de accesos</strong></span></h2>
<p>Para poder acceder restablecer tu contrase&ntilde;a ingresa al siguiente link temporal</p>
<ul style="list-style-type: circle;">
<ul style="list-style-type: circle;">
<li><strong>Usuario: </strong> &nbsp;' . $usuario . '&nbsp;</li>
<li><strong>Link : </strong> &nbsp; &nbsp; &nbsp; <a href="http://adminpos.shopshop.com.gt/index.php/registro/recupaClave?token='.$token.'"><strong><img src="http://adminpos.shopshop.com.gt/images/logo_pdv.png" alt="" width="205" height="70" /></strong></a> &nbsp;&nbsp;</li>
</ul>
</ul>
<p>&nbsp;</p>';
   
        UsuarioPeer::sendEmail($texto, $titulo, $correo);
        
    }


    static public function sendEmail($template, $subject, $to) {
        $urlAPI = "https://mailing.shopshop.com.gt/envio.php";

        $data['correo'] = 'shopshoppruebaxx@gmail.com';
        $data['clave'] = 'shopshop18xx';
        $data['servidor'] = 'smtp.gmail.com';
        $data['puerto'] = '465';
        $data['empresa'] = "VeniaLink";
//        $data['correo_reply'] = $reply;
        $data['correo_cliente'] = $to;
        $data['asunto'] = $subject;
        $data['mensaje'] = $template;

        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_URL => $urlAPI,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => $data
        ));

        $response = curl_exec($curl);
        $response = json_decode($response);
        echo "<pre>";
        print_r($response);
       
        $err = curl_error($curl);
        curl_close($curl);
        return json_decode(json_encode($response));
    }
    
}
