
<?php
//define('LISTA_CATALOGOS', 'List Items');
//define('CATEGORIAS', 'Categorys');
//define('CATEGORIASRESPUESTA', 'Categorys Answers');
//define('SUBCATEGORIAS', 'Sub Categorys');
//define('CATEGORIA_RESPUESTA', 'Category Answers');
//define('CODIGO', 'Code');
//define('NOMBRE', 'Name');
//define('NOMBRE_2', 'Second Name');
//define('ACTIVO', 'Active');
//define('ACCION', 'Action');
//define('OBSERVACIONES', 'Observations');
//define('CONFIRMAR_PROCESO', 'Confirm Process');
//define('CONFIRMAR_ELIMINA', 'Sure delete item');
//define('CONFIRMAR', 'Confirm');
//define('ACEPTAR', 'Accept');
//define('ELIMINAR', 'Delete');
//define('NUEVO_REGISTRO', 'New Item');
//define('EDITA_REGISTRO', 'Edit');
//define('ACTUALIZAR', 'Update');
//define('RETORNAR', 'Return');
//define('CANCELAR', 'Cancel');
//define('MENSAJE_GUARDA', 'Information stored successfully');
//define('MENSAJE_ELIMINA', 'Information deleted successfully');
//define('MENSAJE_ERROR', 'An error has occurred, try again');
//define('USUARIO', 'User');
//define('USUARIOS', 'Users');
//define('NOMBRES', 'Name');
//define('APELLIDOS', 'Last Name');
//define('PAIS', 'Country');
//define('ORGANIZACION', 'Organization');
//define('TIPO_USUARIO', 'Type User');
//define('NIVEL_USUARIO', 'Level User');
//define('CORREO', 'Email');
//define('CLAVE', 'Password');
//define('BIENVENIDO', 'Welcome');
//define('CONFIRMADO', 'Confirmado');
//define('CODIGO_PAIS', 'Código Country');
//define('CODIGO_REGION', 'Código Region');
//define('LISTA', 'List');
define('LISTA_CATALOGOS', 'Listado de Registros');
define('CATEGORIAS', 'Categoría Motivo');
define('CATEGORIASRESPUESTA', 'Categoría Respuesta Motivo');
define('SUBCATEGORIAS', 'Sub Categoría Motivo');
define('CATEGORIA_RESPUESTA', 'Categoría Respuesta Motivo');
define('CODIGO', 'Código');
define('NOMBRE', 'Nombre');
define('NOMBRE_2', 'Nombre 2');
define('ACTIVO', 'Activo');
define('ACCION', 'Acción');
define('OBSERVACIONES', 'Observaciones');
define('CONFIRMAR_PROCESO', 'Confirmación de Proceso');
define('CONFIRMAR_ELIMINA', 'Esta seguro de eliminar Registro');
define('CONFIRMAR', 'Confirmar');
define('ACEPTAR', 'Aceptar');
define('ELIMINAR', 'Eliminar');
define('NUEVO_REGISTRO', 'Nuevo Registro');
define('EDITA_REGISTRO', 'Editar');
define('ACTUALIZAR', 'Actualizar');
define('RETORNAR', 'Retornar');
define('CANCELAR', 'Cancelar');
define('MENSAJE_GUARDA', 'Información almacenada con éxito');
define('MENSAJE_ELIMINA', 'Información  eliminada con éxito');
define('MENSAJE_ERROR', 'Ha ocurrido un error intentelo de nuevo');
define('USUARIO', 'User');
define('USUARIOS', 'Users');
define('NOMBRES', 'Nombres');
define('APELLIDOS', 'Apellidos');
define('PAIS', 'Pais');
define('ORGANIZACION', 'Organización');
define('TIPO_USUARIO', 'Tipo Usuario');
define('NIVEL_USUARIO', 'Nivel Usuario');
define('CORREO', 'Correo');
define('CLAVE', 'Clave');
define('BIENVENIDO', 'Bienvenido');
define('CONFIRMADO', 'Confirmado');
define('CODIGO_PAIS', 'Código Pais');
define('CODIGO_REGION', 'Código Región');
define('LISTA', 'Lista');

?>